(() => {
'use strict';
const T=window.AnatomyTaxonomy;
const BUILTIN_Q=window.QUESTION_BANK||[];
const main=document.getElementById('main'),nav=[...document.querySelectorAll('.nav-item')];
const KEY='ulq-state-v1',SKEY='ulq-settings-v1',SESSION_KEY='ulq-active-session-v2',CUSTOM_KEY='ulq-custom-questions-v1';
const title=document.querySelector('.brand strong'),subtitle=document.querySelector('.brand span');
if(title)title.textContent='反復暗記アプリ';if(subtitle)subtitle.textContent='解剖学クイズ・自作問題';document.title='反復暗記アプリ';
let st=JSON.parse(localStorage.getItem(KEY)||'{"items":{},"answered":0,"correct":0,"streak":0,"last":""}');
let cfg=JSON.parse(localStorage.getItem(SKEY)||'{"order":"smart","showInput":true,"largeText":false}');
let customStore=loadCustomStore(),Q=[],groups=[],sess=null,currentBranch='hub',listFilter={scope:'anatomy',status:'all',major:'all',sub:'all'};
const save=()=>localStorage.setItem(KEY,JSON.stringify(st));
const saveCfg=()=>localStorage.setItem(SKEY,JSON.stringify(cfg));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const item=id=>st.items[id]||(st.items[id]={level:0,due:0,seen:0,ok:0,ng:0});
const meta=q=>T.meta(q);
const day=()=>new Date().toISOString().slice(0,10);
function loadCustomStore(){try{const raw=JSON.parse(localStorage.getItem(CUSTOM_KEY)||'null');if(raw&&Array.isArray(raw.items))return{schemaVersion:1,items:raw.items,updatedAt:Number(raw.updatedAt)||0};if(Array.isArray(raw))return{schemaVersion:1,items:raw,updatedAt:Date.now()};}catch{}return{schemaVersion:1,items:[],updatedAt:0}}
function activeCustom(){return customStore.items.filter(q=>q&&!q.deleted&&q.question&&q.answer).map(q=>({...q,custom:true,expected:Math.max(1,Number(q.expected)||1),category:q.category||'自作',note:q.note||''}))}
function rebuild(){Q=[...BUILTIN_Q,...activeCustom()];groups=T.build(Q)}
function saveCustom(){customStore.schemaVersion=1;customStore.updatedAt=Date.now();localStorage.setItem(CUSTOM_KEY,JSON.stringify(customStore));rebuild()}
rebuild();
function touchStreak(){const t=day();if(st.last===t)return;const y=new Date();y.setDate(y.getDate()-1);st.streak=st.last===y.toISOString().slice(0,10)?(st.streak||0)+1:1;st.last=t;}
function summary(list=Q){let mastered=0,unseen=0,due=0;const now=Date.now();list.forEach(q=>{const s=st.items[q.id];if(!s||!s.seen)unseen++;else if(s.level>=4)mastered++;if(s&&s.seen&&s.due<=now)due++;});return{mastered,unseen,due,accuracy:st.answered?Math.round(st.correct/st.answered*100):0,total:list.length};}
function stat(list){const m=list.filter(q=>(st.items[q.id]?.level||0)>=4).length,d=list.filter(q=>st.items[q.id]?.seen&&st.items[q.id].due<=Date.now()).length;return{m,d,n:list.length,p:list.length?Math.round(m/list.length*100):0};}
function group(id){return groups.find(g=>g.id===id)}
function groupsForScope(scope){return groups.filter(g=>scope==='custom'?g.id==='custom':g.id!=='custom')}
function questionsForScope(scope){return Q.filter(q=>scope==='custom'?meta(q).majorId==='custom':meta(q).majorId!=='custom')}
function sessionPayload(){if(!sess)return null;return{queueIds:sess.queue.map(q=>q.id),i:sess.i,mode:sess.mode,score:sess.score,options:sess.options||{},history:sess.history||[],stage:sess.stage||'question',draft:sess.draft||'',choiceResult:sess.choiceResult||null,updatedAt:Date.now()};}
function saveActiveSession(){const payload=sessionPayload();if(payload)localStorage.setItem(SESSION_KEY,JSON.stringify(payload));else localStorage.removeItem(SESSION_KEY);}
function clearActiveSession(){sess=null;localStorage.removeItem(SESSION_KEY);}
function restoreActiveSession(){let raw;try{raw=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');}catch{localStorage.removeItem(SESSION_KEY);return null}if(!raw||!Array.isArray(raw.queueIds)||!raw.queueIds.length)return null;const queue=raw.queueIds.map(id=>Q.find(q=>q.id==id)).filter(Boolean);if(queue.length!==raw.queueIds.length){localStorage.removeItem(SESSION_KEY);return null}const i=Math.max(0,Math.min(Number(raw.i)||0,queue.length-1));currentBranch=queue.some(q=>meta(q).majorId==='custom')?'custom':'anatomy';return{queue,i,mode:raw.mode||'recall',score:Number(raw.score)||0,options:raw.options||{},history:Array.isArray(raw.history)?raw.history:[],stage:raw.stage||'question',draft:String(raw.draft||''),choiceResult:raw.choiceResult||null};}
function hasActiveSession(){return Boolean(sess&&sess.queue?.length)}
function resumeLabel(){return sess?.stage==='finished'?'結果画面に戻る':'続きから始める'}
function resumeSession(){if(!hasActiveSession())return go('hub');if(sess.stage==='finished')finish(true);else question();}
function setNav(active){nav.forEach(b=>b.classList.toggle('active',b.dataset.view===active))}
function go(view,opt={}){if(view==='hub'){currentBranch='hub';setNav('home');hub()}else if(view==='anatomy'){currentBranch='anatomy';anatomyHome()}else if(view==='custom'){currentBranch='custom';customHome()}else{if(currentBranch==='hub')currentBranch='anatomy';if(view==='home')currentBranch==='custom'?customHome():anatomyHome();if(view==='topic')topic(opt.major);if(view==='study')setup(opt);if(view==='list')list();if(view==='stats')stats();}scrollTo(0,0);}
function hub(){const a=summary(questionsForScope('anatomy')),c=summary(questionsForScope('custom'));const resume=hasActiveSession()?`<section class="resume-session-card"><div><span>進行中のクイズ</span><strong>${sess.i+1}/${sess.queue.length}問目${sess.stage==='finished'?'・完了':''}</strong><small>${esc(meta(sess.queue[Math.min(sess.i,sess.queue.length-1)]).major)}から再開できます</small></div><button class="primary-btn" id="resumeSession">${resumeLabel()}</button></section>`:'';main.innerHTML=`${resume}<section class="hero"><div class="hero-kicker">反復暗記アプリ</div><h1>学習する内容を<br>選ぶ</h1><p>解剖学の既存問題と、自分で作る暗記カードを分けて学習できます。</p></section><div class="major-grid"><button class="major-card" id="openAnatomy"><div class="major-card-head"><strong>解剖学クイズ</strong><span>${a.total}問</span></div><p>大分類・小分類から選んで、既存の解剖学問題を復習します。</p><small>${a.mastered}/${a.total} 定着 ・ 復習 ${a.due}問</small><div class="major-card-foot">開く <b>›</b></div></button><button class="major-card" id="openCustom"><div class="major-card-head"><strong>自作問題</strong><span>${c.total}問</span></div><p>Ankiのように、自分で問題と答えを追加して反復学習します。</p><small>${c.mastered}/${c.total} 定着 ・ 復習 ${c.due}問</small><div class="major-card-foot">作る・学ぶ <b>›</b></div></button></div>`;const r=document.getElementById('resumeSession');if(r)r.onclick=resumeSession;document.getElementById('openAnatomy').onclick=()=>go('anatomy');document.getElementById('openCustom').onclick=()=>go('custom');}
function anatomyHome(){currentBranch='anatomy';setNav('home');const anatomy=questionsForScope('anatomy'),s=summary(anatomy);const resume=hasActiveSession()?`<section class="resume-session-card"><div><span>進行中のクイズ</span><strong>${sess.i+1}/${sess.queue.length}問目${sess.stage==='finished'?'・完了':''}</strong><small>${esc(meta(sess.queue[Math.min(sess.i,sess.queue.length-1)]).major)}${sess.stage==='finished'?'の結果を確認できます':'から再開できます'}</small></div><button class="primary-btn" id="resumeSession">${resumeLabel()}</button></section>`:'';main.innerHTML=`<button class="text-back" id="backHub">‹ 反復暗記アプリへ</button>${resume}<section class="hero"><div class="hero-kicker">解剖学クイズ</div><h1>${s.due?`復習が ${s.due} 問<br>あります`:`全${anatomy.length}問を<br>定着させる`}</h1><p>大分類から入り、小分類を絞って弱点を重点的に復習できます。</p><div class="hero-actions"><button class="primary-btn" id="quick">${s.due?'今日の復習':'10問始める'}</button><button class="secondary-btn" id="custom">条件を選ぶ</button></div></section><div class="section-title"><h2>進捗</h2><span>自動保存</span></div><div class="stat-grid"><div class="stat-card"><b>${s.mastered}</b><span>定着</span></div><div class="stat-card"><b>${s.accuracy}%</b><span>正答率</span></div><div class="stat-card"><b>${st.streak||0}日</b><span>連続学習</span></div></div><div class="section-title"><h2>大分類から選ぶ</h2><span>選択後に小分類を表示</span></div><div class="major-grid">${groupsForScope('anatomy').map(g=>{const x=stat(g.questions);return`<button class="major-card" data-major="${g.id}"><div class="major-card-head"><strong>${esc(g.name)}</strong><span>${x.n}問</span></div><p>${esc(g.description)}</p><small>${x.m}/${x.n} 定着 ・ 復習 ${x.d}問</small><div class="mini-progress"><i style="width:${x.p}%"></i></div><div class="major-card-foot">小分類を見る <b>›</b></div></button>`}).join('')}</div>`;document.getElementById('backHub').onclick=()=>go('hub');const resumeBtn=document.getElementById('resumeSession');if(resumeBtn)resumeBtn.onclick=resumeSession;document.getElementById('quick').onclick=()=>start({scope:'anatomy',pool:s.due?'due':'smart',count:10,mode:'recall',major:'all',sub:'all'});document.getElementById('custom').onclick=()=>go('study',{scope:'anatomy'});document.querySelectorAll('[data-major]').forEach(b=>b.onclick=()=>go('topic',{major:b.dataset.major}));}
function customHome(){currentBranch='custom';setNav('home');const custom=questionsForScope('custom'),s=summary(custom);main.innerHTML=`<button class="text-back" id="backHub">‹ 反復暗記アプリへ</button><section class="hero"><div class="hero-kicker">自作問題</div><h1>${custom.length?`${custom.length}問を<br>反復学習`:'問題を<br>追加する'}</h1><p>質問と答えを登録すると、自作問題として出題できます。Google同期にも含まれます。</p><div class="hero-actions"><button class="primary-btn" id="studyCustom" ${custom.length?'':'disabled'}>自作問題を10問</button><button class="secondary-btn" id="setupCustom" ${custom.length?'':'disabled'}>条件を選ぶ</button></div></section><section class="panel"><h2>自作問題を追加</h2><div class="form-grid"><div class="field field-wide"><label>問題</label><textarea id="customQuestion" class="answer-input" rows="3" placeholder="例：大胸筋の支配神経は？"></textarea></div><div class="field field-wide"><label>答え</label><textarea id="customAnswer" class="answer-input" rows="3" placeholder="例：外側胸筋神経、内側胸筋神経の一部"></textarea></div><div class="field"><label>小分類</label><input id="customCategory" class="searchbox" placeholder="例：上肢の筋" value="自作"></div><div class="field"><label>目安項目数</label><input id="customExpected" class="searchbox" type="number" min="1" value="1"></div></div><button class="primary-btn" id="addCustomQuestion" style="width:100%;margin-top:14px">追加する</button></section><div class="section-title"><h2>自作問題一覧</h2><span>${s.mastered}/${s.total} 定着</span></div><div class="question-list">${custom.length?custom.slice().sort((a,b)=>b.id-a.id).map(q=>{const m=meta(q);return`<div class="question-row"><button data-custom-open="${q.id}" style="all:unset;display:block;width:100%;cursor:pointer"><strong>Q${q.id} ・ ${esc(m.sub)}</strong><p>${esc(q.question)}</p></button><button class="text-btn" data-custom-delete="${q.id}" type="button">削除</button></div>`}).join(''):'<div class="empty">まだ自作問題がありません</div>'}</div>`;document.getElementById('backHub').onclick=()=>go('hub');document.getElementById('studyCustom').onclick=()=>start({scope:'custom',major:'custom',sub:'all',pool:s.due?'due':'smart',count:10,mode:'recall'});document.getElementById('setupCustom').onclick=()=>go('study',{scope:'custom',major:'custom'});document.getElementById('addCustomQuestion').onclick=addCustomQuestion;document.querySelectorAll('[data-custom-open]').forEach(b=>b.onclick=()=>openSingle(Number(b.dataset.customOpen)));document.querySelectorAll('[data-custom-delete]').forEach(b=>b.onclick=()=>deleteCustomQuestion(Number(b.dataset.customDelete)));}
function addCustomQuestion(){const question=document.getElementById('customQuestion').value.trim(),answer=document.getElementById('customAnswer').value.trim(),category=document.getElementById('customCategory').value.trim()||'自作',expected=Math.max(1,Number(document.getElementById('customExpected').value)||1);if(!question||!answer){alert('問題と答えを入力してください');return}const now=Date.now(),id=now*1000+Math.floor(Math.random()*1000);customStore.items.push({id,question,answer,category,expected,note:'',custom:true,createdAt:now,updatedAt:now});saveCustom();customHome();}
function deleteCustomQuestion(id){const q=customStore.items.find(x=>Number(x.id)===id);if(!q)return;if(!confirm('この自作問題を削除しますか？'))return;q.deleted=true;q.updatedAt=Date.now();delete st.items[id];save();if(sess?.queue?.some(x=>Number(x.id)===id))clearActiveSession();saveCustom();customHome();}
function openSingle(id){const q=Q.find(x=>Number(x.id)===id);if(!q)return;sess={queue:[q],i:0,mode:'recall',score:0,options:{scope:meta(q).majorId==='custom'?'custom':'anatomy',major:'all',sub:'all',pool:'all',count:1},history:[],stage:'question',draft:'',choiceResult:null};saveActiveSession();question()}
function topic(majorId){const g=group(majorId);if(!g){go(currentBranch==='custom'?'custom':'anatomy');return}currentBranch=g.id==='custom'?'custom':'anatomy';const x=stat(g.questions);main.innerHTML=`<button class="text-back" id="backHome">‹ ${currentBranch==='custom'?'自作問題':'大分類'}へ戻る</button><section class="topic-hero"><div><span>${x.n}問</span><h1>${esc(g.name)}</h1><p>${esc(g.description)}</p></div><div class="topic-score"><b>${x.p}%</b><small>定着</small></div></section><div class="topic-actions"><button class="primary-btn" id="studyMajor">${esc(g.name)}を10問</button><button class="secondary-btn" id="setupMajor">条件を指定</button></div><div class="section-title"><h2>小分類</h2><span>重点復習する分野を選択</span></div><div class="subcategory-list">${g.subs.map(s=>{const a=stat(s.questions);return`<button class="subcategory-card" data-sub="${esc(s.name)}"><div><strong>${esc(s.name)}</strong><small>${a.n}問 ・ 定着 ${a.m}問 ・ 復習 ${a.d}問</small></div><div class="sub-progress"><i style="width:${a.p}%"></i></div><span class="sub-arrow">›</span></button>`}).join('')}</div>`;document.getElementById('backHome').onclick=()=>go(currentBranch==='custom'?'custom':'anatomy');document.getElementById('studyMajor').onclick=()=>start({scope:currentBranch,major:g.id,sub:'all',pool:'smart',count:10,mode:'recall'});document.getElementById('setupMajor').onclick=()=>go('study',{scope:currentBranch,major:g.id});document.querySelectorAll('[data-sub]').forEach(b=>b.onclick=()=>go('study',{scope:currentBranch,major:g.id,sub:b.dataset.sub}));}
function subOptions(majorId,selected='all'){if(majorId==='all')return'<option value="all">全小分類</option>';const g=group(majorId);return`<option value="all">${esc(g.name)}の全問題</option>${g.subs.map(s=>`<option value="${esc(s.name)}" ${s.name===selected?'selected':''}>${esc(s.name)}（${s.questions.length}問）</option>`).join('')}`;}
function setup(o={}){const scope=o.scope||currentBranch==='custom'?'custom':'anatomy';currentBranch=scope;setNav('study');const available=groupsForScope(scope),selectedMajor=o.major||(scope==='custom'?'custom':'all'),selectedSub=o.sub||'all';main.innerHTML=`<section class="panel"><h2>${scope==='custom'?'自作問題':'解剖学クイズ'}の学習条件</h2><div class="form-grid two"><div class="field"><label>大分類</label><select id="major">${scope==='custom'?'': '<option value="all">全大分類</option>'}${available.map(g=>`<option value="${g.id}" ${g.id===selectedMajor?'selected':''}>${esc(g.name)}（${g.questions.length}問）</option>`).join('')}</select></div><div class="field"><label>小分類</label><select id="sub">${subOptions(selectedMajor,selectedSub)}</select></div><div class="field"><label>出題形式</label><select id="mode"><option value="recall">思い出す</option><option value="choice">四択</option></select></div><div class="field"><label>問題数</label><select id="count"><option>10</option><option>20</option><option>30</option><option>50</option><option value="all">全問</option></select></div><div class="field field-wide"><label>対象</label><select id="pool"><option value="smart">弱点・未学習を優先</option><option value="due">復習期限</option><option value="unseen">未学習</option><option value="weak">間違えた問題</option><option value="all">全問題</option></select></div></div><div class="selection-summary" id="selectionSummary"></div><button class="primary-btn" id="begin" style="width:100%;margin-top:14px">開始する</button></section>`;const majorEl=document.getElementById('major'),subEl=document.getElementById('sub');const refresh=()=>{const a=filtered({scope,major:majorEl.value,sub:subEl.value});document.getElementById('selectionSummary').textContent=`選択範囲：${a.length}問`;};majorEl.onchange=()=>{subEl.innerHTML=subOptions(majorEl.value);refresh()};subEl.onchange=refresh;refresh();document.getElementById('begin').onclick=()=>start({scope,mode:document.getElementById('mode').value,count:document.getElementById('count').value,major:majorEl.value,sub:subEl.value,pool:document.getElementById('pool').value});}
function filtered(o={}){const scope=o.scope||currentBranch==='custom'?'custom':'anatomy';return Q.filter(q=>{const m=meta(q);if(scope==='custom'&&m.majorId!=='custom')return false;if(scope==='anatomy'&&m.majorId==='custom')return false;return(!o.major||o.major==='all'||m.majorId===o.major)&&(!o.sub||o.sub==='all'||m.sub===o.sub)})}
function pick(o){const now=Date.now();let a=filtered(o);if(o.pool==='due')a=a.filter(q=>item(q.id).seen&&item(q.id).due<=now);if(o.pool==='unseen')a=a.filter(q=>!item(q.id).seen);if(o.pool==='weak')a=a.filter(q=>item(q.id).ng>0&&item(q.id).level<4);const score=q=>{const s=item(q.id);return(!s.seen?1000:0)+(s.due<=now?500:0)+s.ng*20-s.level*35+Math.random()*10};if(cfg.order==='number')a.sort((x,y)=>x.id-y.id);else if(cfg.order==='random')a.sort(()=>Math.random()-.5);else a.sort((x,y)=>score(y)-score(x));return a.slice(0,o.count==='all'?a.length:+o.count);}
function start(o){const queue=pick(o);if(!queue.length){alert('条件に合う問題がありません');return}currentBranch=o.scope==='custom'?'custom':'anatomy';sess={queue,i:0,mode:o.mode||'recall',score:0,options:{...o},history:[],stage:'question',draft:'',choiceResult:null};saveActiveSession();question();}
function canUndo(){return Boolean(sess?.history?.length)}
function question(){if(!sess||!sess.queue?.length)return go('hub');sess.history=sess.history||[];if(sess.stage==='finished')return finish(true);setNav('study');const q=sess.queue[sess.i],m=meta(q);main.innerHTML=`<div class="study-head"><div class="progress-track"><i style="width:${sess.i/sess.queue.length*100}%"></i></div><span>${sess.i+1}/${sess.queue.length}</span>${canUndo()?'<button class="study-undo-btn" id="undoQuestion" type="button">↶ 1問戻る</button>':''}</div><section class="question-card"><div class="q-meta"><span class="badge">Q${q.id}</span><span class="badge major-badge">${esc(m.major)}</span><span class="badge sub-badge">${esc(m.sub)}</span>${q.note?'<span class="badge warn">要確認</span>':''}</div><div class="question-text">${esc(q.question)}</div><div id="work"></div></section>`;const undo=document.getElementById('undoQuestion');if(undo)undo.onclick=undoLast;sess.mode==='choice'?choices(q):recall(q);}
function recall(q){const workEl=document.getElementById('work');workEl.innerHTML=`${cfg.showInput?`<textarea class="answer-input" placeholder="答えを書き出す"></textarea><div class="hint-text">目安：${q.expected}項目</div>`:''}<div id="ans"></div><div class="question-actions" id="actions"><button class="primary-btn" id="show">答えを表示</button></div>`;const input=workEl.querySelector('.answer-input');if(input){input.value=sess.draft||'';input.addEventListener('input',()=>{sess.draft=input.value;saveActiveSession()});}if(sess.stage==='answer')return showRecallAnswer(q);document.getElementById('show').onclick=()=>{sess.stage='answer';saveActiveSession();showRecallAnswer(q)};}
function showRecallAnswer(q){document.getElementById('ans').innerHTML=answerBox(q);document.getElementById('actions').innerHTML=`<div class="grade-grid"><button class="grade-btn grade-skip" id="skipQuestion"><b>スキップ</b><small>記録しない</small></button><button class="grade-btn grade-again" data-g="again"><b>不正解</b><small>すぐ</small></button><button class="grade-btn grade-hard" data-g="hard"><b>曖昧</b><small>明日</small></button><button class="grade-btn grade-good" data-g="good"><b>正解</b><small>数日後</small></button><button class="grade-btn grade-easy" data-g="easy"><b>余裕</b><small>長め</small></button></div>`;document.getElementById('skipQuestion').onclick=skipCurrent;document.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>grade(q,b.dataset.g));}
function answerBox(q){return`<div class="answer-box"><div class="answer-label">回答</div><div class="answer-text">${esc(q.answer).replaceAll('／','<br>')}</div>${q.note?`<div class="source-note">${esc(q.note)}</div>`:''}</div>`;}
function choiceAnswers(q){const m=meta(q);let candidates=Q.filter(x=>x.id!==q.id&&meta(x).sub===m.sub&&meta(x).majorId===m.majorId);if(candidates.length<3)candidates=Q.filter(x=>x.id!==q.id&&meta(x).majorId===m.majorId);if(candidates.length<3)candidates=filtered({scope:m.majorId==='custom'?'custom':'anatomy'}).filter(x=>x.id!==q.id);let answers=candidates.sort(()=>Math.random()-.5).slice(0,3).map(x=>x.answer);return[q.answer,...answers].sort(()=>Math.random()-.5);}
function choices(q){if(!sess.choiceResult?.answers)sess.choiceResult={answers:choiceAnswers(q),selected:null,ok:null};const result=sess.choiceResult;document.getElementById('work').innerHTML=`<div class="choice-list">${result.answers.map(x=>`<button class="choice-btn" data-v="${encodeURIComponent(x)}">${esc(x)}</button>`).join('')}</div><div id="ans"></div>`;if(sess.stage==='choice-reviewed')return renderChoiceResult(q);document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>selectChoice(q,b));saveActiveSession();}
function selectChoice(q,button){const selected=decodeURIComponent(button.dataset.v),ok=selected===q.answer;pushHistory(q);record(q,ok?'good':'again');if(ok)sess.score++;sess.stage='choice-reviewed';sess.choiceResult={answers:sess.choiceResult.answers,selected,ok};saveActiveSession();renderChoiceResult(q);}
function renderChoiceResult(q){const result=sess.choiceResult;document.querySelectorAll('[data-v]').forEach(x=>{x.disabled=true;const value=decodeURIComponent(x.dataset.v),right=value===q.answer;x.classList.toggle('correct',right);x.classList.toggle('wrong',value===result.selected&&!result.ok)});document.getElementById('ans').innerHTML=answerBox(q)+`<div class="question-actions"><button class="primary-btn" id="next">次へ</button></div>`;document.getElementById('next').onclick=advance;}
function snapshotItem(id){return st.items[id]?{...st.items[id]}:null}
function pushHistory(q){sess.history=sess.history||[];sess.history.push({i:sess.i,qid:q.id,item:snapshotItem(q.id),answered:st.answered,correct:st.correct,streak:st.streak,last:st.last,score:sess.score,stage:sess.stage,draft:sess.draft||'',choiceResult:sess.choiceResult?JSON.parse(JSON.stringify(sess.choiceResult)):null});}
function grade(q,g){pushHistory(q);record(q,g);if(g==='good'||g==='easy')sess.score++;advance()}
function skipCurrent(){const q=sess.queue[sess.i];pushHistory(q);advance()}
function undoLast(){const previous=sess?.history?.pop();if(!previous)return;if(previous.item===null)delete st.items[previous.qid];else st.items[previous.qid]={...previous.item};st.answered=previous.answered;st.correct=previous.correct;st.streak=previous.streak;st.last=previous.last;sess.score=previous.score;sess.i=previous.i;sess.stage=previous.stage||'question';sess.draft=previous.draft||'';sess.choiceResult=previous.choiceResult||null;save();saveActiveSession();question();}
function record(q,g){const s=item(q.id),now=Date.now();s.seen++;st.answered++;if(g==='again'){s.level=Math.max(0,s.level-1);s.ng++;s.due=now+300000}if(g==='hard'){s.ng++;s.due=now+86400000}if(g==='good'){s.level=Math.min(5,s.level+1);s.ok++;st.correct++;s.due=now+[1,2,4,8,16,30][s.level]*86400000}if(g==='easy'){s.level=Math.min(5,s.level+2);s.ok++;st.correct++;s.due=now+[2,4,8,16,30,60][s.level]*86400000}touchStreak();save()}
function advance(){sess.i++;sess.stage='question';sess.draft='';sess.choiceResult=null;if(sess.i<sess.queue.length){saveActiveSession();question()}else{sess.i=sess.queue.length-1;sess.stage='finished';saveActiveSession();finish(true)}}
function finish(){if(!sess)return go('hub');sess.stage='finished';saveActiveSession();setNav('study');const opts={...sess.options,count:10};main.innerHTML=`<section class="hero"><div class="hero-kicker">SESSION COMPLETE</div><h1>${sess.queue.length}問 完了</h1><p>正解・余裕：${sess.score}問</p><div class="hero-actions">${canUndo()?'<button class="secondary-btn" id="undoFinished">1問戻る</button>':''}<button class="primary-btn" id="again">同じ分野を10問</button><button class="secondary-btn" id="back">戻る</button></div></section>`;const undo=document.getElementById('undoFinished');if(undo)undo.onclick=undoLast;document.getElementById('again').onclick=()=>start(opts);document.getElementById('back').onclick=()=>{clearActiveSession();go(currentBranch==='custom'?'custom':'anatomy')}}
function list(){const scope=currentBranch==='custom'?'custom':'anatomy';setNav('list');if(listFilter.scope!==scope)listFilter={scope,status:'all',major:scope==='custom'?'custom':'all',sub:'all'};const available=groupsForScope(scope);main.innerHTML=`<div class="list-toolbar"><input id="search" class="searchbox" placeholder="問題・回答を検索"><div class="list-selects"><select id="listMajor">${scope==='custom'?'':'<option value="all">全大分類</option>'}${available.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}</select><select id="listSub"><option value="all">全小分類</option></select></div><div class="filter-row"><button class="chip active" data-status="all">すべて</button><button class="chip" data-status="weak">弱点</button><button class="chip" data-status="mastered">定着</button><button class="chip" data-status="unseen">未学習</button></div></div><div id="rows" class="question-list"></div>`;const searchEl=document.getElementById('search'),majorEl=document.getElementById('listMajor'),subEl=document.getElementById('listSub'),rowsEl=document.getElementById('rows');const updateSubs=()=>{subEl.innerHTML=subOptions(majorEl.value,listFilter.sub);if(![...subEl.options].some(o=>o.value===listFilter.sub))listFilter.sub='all';subEl.value=listFilter.sub};const draw=()=>{const text=searchEl.value.toLowerCase();let a=filtered(listFilter).filter(q=>(q.question+' '+q.answer).toLowerCase().includes(text));if(listFilter.status==='weak')a=a.filter(q=>(st.items[q.id]?.ng||0)>0);if(listFilter.status==='mastered')a=a.filter(q=>(st.items[q.id]?.level||0)>=4);if(listFilter.status==='unseen')a=a.filter(q=>!(st.items[q.id]?.seen));rowsEl.innerHTML=a.length?a.map(q=>{const m=meta(q);return`<button class="question-row" data-id="${q.id}"><strong>Q${q.id} ・ ${esc(m.major)}</strong><small>${esc(m.sub)}</small><p>${esc(q.question)}</p></button>`}).join(''):'<div class="empty">該当する問題がありません</div>';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openSingle(Number(b.dataset.id)))};majorEl.value=listFilter.major;updateSubs();searchEl.oninput=draw;majorEl.onchange=()=>{listFilter.major=majorEl.value;listFilter.sub='all';updateSubs();draw()};subEl.onchange=()=>{listFilter.sub=subEl.value;draw()};document.querySelectorAll('[data-status]').forEach(b=>{b.classList.toggle('active',b.dataset.status===listFilter.status);b.onclick=()=>{listFilter.status=b.dataset.status;document.querySelectorAll('[data-status]').forEach(x=>x.classList.toggle('active',x===b));draw()}});draw();}
function stats(){const scope=currentBranch==='custom'?'custom':'anatomy',s=summary(questionsForScope(scope));setNav('stats');main.innerHTML=`<div class="stat-grid"><div class="stat-card"><b>${st.answered||0}</b><span>総回答</span></div><div class="stat-card"><b>${s.accuracy}%</b><span>正答率</span></div><div class="stat-card"><b>${s.mastered}</b><span>定着</span></div></div><div class="section-title"><h2>${scope==='custom'?'自作問題':'解剖学クイズ'}の分類別</h2></div><div class="stats-groups">${groupsForScope(scope).map(g=>{const x=stat(g.questions);return`<section class="panel stats-group"><div class="stats-group-head"><div><h3>${esc(g.name)}</h3><small>${x.m}/${x.n} 定着</small></div><b>${x.p}%</b></div>${g.subs.map(sub=>{const a=stat(sub.questions);return`<div class="bar-row"><span>${esc(sub.name)}</span><div class="bar"><i style="width:${a.p}%"></i></div><b>${a.p}%</b></div>`}).join('')}</section>`}).join('')}</div>`;}
nav.forEach(b=>b.onclick=()=>go(b.dataset.view));
document.getElementById('homeBtn').onclick=()=>go('hub');document.getElementById('settingsBtn').onclick=()=>document.getElementById('settingsDialog').showModal();
const orderSetting=document.getElementById('orderSetting'),inputSetting=document.getElementById('inputSetting'),largeTextSetting=document.getElementById('largeTextSetting'),resetBtn=document.getElementById('resetBtn');
orderSetting.value=cfg.order;inputSetting.checked=cfg.showInput;largeTextSetting.checked=cfg.largeText;document.body.classList.toggle('large-text',cfg.largeText);
orderSetting.onchange=()=>{cfg.order=orderSetting.value;saveCfg()};inputSetting.onchange=()=>{cfg.showInput=inputSetting.checked;saveCfg()};largeTextSetting.onchange=()=>{cfg.largeText=largeTextSetting.checked;document.body.classList.toggle('large-text',cfg.largeText);saveCfg()};resetBtn.onclick=()=>{if(confirm('学習履歴を消去しますか？')){st={items:{},answered:0,correct:0,streak:0,last:''};save();clearActiveSession();document.getElementById('settingsDialog').close();go('hub')}};
addEventListener('pagehide',saveActiveSession);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveActiveSession()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
sess=restoreActiveSession();if(sess)resumeSession();else go('hub');
})();
