(() => {
const Q=window.QUESTION_BANK||[],main=document.getElementById('main'),nav=[...document.querySelectorAll('.nav-item')],cats=[...new Set(Q.map(x=>x.category))];
const KEY='ulq-state-v1',SKEY='ulq-settings-v1';
let st=JSON.parse(localStorage.getItem(KEY)||'{"items":{},"answered":0,"correct":0,"streak":0,"last":""}');
let cfg=JSON.parse(localStorage.getItem(SKEY)||'{"order":"smart","showInput":true,"largeText":false}');
let sess=null,filter='all';
const save=()=>localStorage.setItem(KEY,JSON.stringify(st));
const saveCfg=()=>localStorage.setItem(SKEY,JSON.stringify(cfg));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const item=id=>st.items[id]||(st.items[id]={level:0,due:0,seen:0,ok:0,ng:0});
const day=()=>new Date().toISOString().slice(0,10);
function touchStreak(){const t=day();if(st.last===t)return;const y=new Date();y.setDate(y.getDate()-1);st.streak=st.last===y.toISOString().slice(0,10)?(st.streak||0)+1:1;st.last=t;}
function summary(){let mastered=0,unseen=0,due=0;const now=Date.now();Q.forEach(q=>{const s=st.items[q.id];if(!s||!s.seen)unseen++;else if(s.level>=4)mastered++;if(s&&s.seen&&s.due<=now)due++;});return{mastered,unseen,due,accuracy:st.answered?Math.round(st.correct/st.answered*100):0};}
function catStat(c){const a=Q.filter(q=>q.category===c),m=a.filter(q=>(st.items[q.id]?.level||0)>=4).length;return{m,n:a.length,p:Math.round(m/a.length*100)};}
function go(v,opt={}){nav.forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='home')home();if(v==='study')setup(opt);if(v==='list')list();if(v==='stats')stats();scrollTo(0,0);}
function home(){const s=summary();main.innerHTML=`<section class="hero"><div class="hero-kicker">SPACED REPETITION</div><h1>${s.due?`復習が ${s.due} 問<br>あります`:'上肢121問を<br>定着させる'}</h1><p>答えを見る前に思い出し、曖昧を正解扱いしない。記憶の弱い問題ほど早く再出題します。</p><div class="hero-actions"><button class="primary-btn" id="quick">${s.due?'今日の復習':'10問始める'}</button><button class="secondary-btn" id="custom">条件を選ぶ</button></div></section><div class="section-title"><h2>進捗</h2><span>自動保存</span></div><div class="stat-grid"><div class="stat-card"><b>${s.mastered}</b><span>定着</span></div><div class="stat-card"><b>${s.accuracy}%</b><span>正答率</span></div><div class="stat-card"><b>${st.streak||0}日</b><span>連続学習</span></div></div><div class="section-title"><h2>分野別</h2></div><div class="category-grid">${cats.map(c=>{const x=catStat(c);return`<button class="category-card" data-cat="${esc(c)}"><strong>${esc(c)}</strong><small>${x.m}/${x.n} 定着</small><div class="mini-progress"><i style="width:${x.p}%"></i></div></button>`}).join('')}</div>`;document.getElementById('quick').onclick=()=>start({pool:s.due?'due':'smart',count:10,mode:'recall'});document.getElementById('custom').onclick=()=>go('study');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>go('study',{cat:b.dataset.cat}));}
function setup(o={}){main.innerHTML=`<section class="panel"><h2>学習条件</h2><div class="form-grid"><div class="field"><label>出題形式</label><select id="mode"><option value="recall">思い出す</option><option value="choice">四択</option></select></div><div class="field"><label>問題数</label><select id="count"><option>10</option><option>20</option><option>30</option><option value="all">全問</option></select></div><div class="field"><label>分野</label><select id="cat"><option value="all">全分野</option>${cats.map(c=>`<option ${c===o.cat?'selected':''}>${esc(c)}</option>`).join('')}</select></div><div class="field"><label>対象</label><select id="pool"><option value="smart">弱点・未学習を優先</option><option value="due">復習期限</option><option value="unseen">未学習</option><option value="weak">間違えた問題</option><option value="all">全問題</option></select></div></div><button class="primary-btn" id="begin" style="width:100%;margin-top:18px">開始する</button></section>`;document.getElementById('begin').onclick=()=>start({mode:mode.value,count:count.value,cat:cat.value,pool:pool.value});}
function pick(o){const now=Date.now();let a=Q.filter(q=>!o.cat||o.cat==='all'||q.category===o.cat);if(o.pool==='due')a=a.filter(q=>item(q.id).seen&&item(q.id).due<=now);if(o.pool==='unseen')a=a.filter(q=>!item(q.id).seen);if(o.pool==='weak')a=a.filter(q=>item(q.id).ng>0&&item(q.id).level<4);const score=q=>{const s=item(q.id);return(!s.seen?1000:0)+(s.due<=now?500:0)+s.ng*20-s.level*35+Math.random()*10};if(cfg.order==='number')a.sort((x,y)=>x.id-y.id);else if(cfg.order==='random')a.sort(()=>Math.random()-.5);else a.sort((x,y)=>score(y)-score(x));return a.slice(0,o.count==='all'?a.length:+o.count);}
function start(o){const queue=pick(o);if(!queue.length){alert('条件に合う問題がありません');return;}sess={queue,i:0,mode:o.mode||'recall',score:0};question();}
function question(){const q=sess.queue[sess.i];main.innerHTML=`<div class="study-head"><div class="progress-track"><i style="width:${sess.i/sess.queue.length*100}%"></i></div><span>${sess.i+1}/${sess.queue.length}</span></div><section class="question-card"><div class="q-meta"><span class="badge">Q${q.id}</span><span class="badge">${esc(q.category)}</span>${q.note?'<span class="badge warn">要確認</span>':''}</div><div class="question-text">${esc(q.question)}</div><div id="work"></div></section>`;sess.mode==='choice'?choices(q):recall(q);}
function recall(q){work.innerHTML=`${cfg.showInput?`<textarea class="answer-input" placeholder="答えを書き出す"></textarea><div class="hint-text">目安：${q.expected}項目</div>`:''}<div id="ans"></div><div class="question-actions" id="actions"><button class="primary-btn" id="show">答えを表示</button></div>`;show.onclick=()=>{ans.innerHTML=answerBox(q);actions.innerHTML=`<div class="grade-grid"><button class="grade-btn grade-again" data-g="again"><b>不正解</b><small>すぐ</small></button><button class="grade-btn grade-hard" data-g="hard"><b>曖昧</b><small>明日</small></button><button class="grade-btn grade-good" data-g="good"><b>正解</b><small>数日後</small></button><button class="grade-btn grade-easy" data-g="easy"><b>余裕</b><small>長め</small></button></div>`;document.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>grade(q,b.dataset.g));};}
function answerBox(q){return`<div class="answer-box"><div class="answer-label">資料の回答</div><div class="answer-text">${esc(q.answer).replaceAll('／','<br>')}</div>${q.note?`<div class="source-note">${esc(q.note)}</div>`:''}</div>`;}
function choices(q){let a=Q.filter(x=>x.id!==q.id&&x.category===q.category).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.answer);a=[q.answer,...a].sort(()=>Math.random()-.5);work.innerHTML=`<div class="choice-list">${a.map(x=>`<button class="choice-btn" data-v="${encodeURIComponent(x)}">${esc(x)}</button>`).join('')}</div><div id="ans"></div>`;document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{const ok=decodeURIComponent(b.dataset.v)===q.answer;document.querySelectorAll('[data-v]').forEach(x=>{x.disabled=true;const right=decodeURIComponent(x.dataset.v)===q.answer;x.classList.toggle('correct',right);if(x===b&&!ok)x.classList.add('wrong')});ans.innerHTML=answerBox(q)+`<div class="question-actions"><button class="primary-btn" id="next">次へ</button></div>`;record(q,ok?'good':'again');if(ok)sess.score++;next.onclick=advance;});}
function grade(q,g){record(q,g);if(g==='good'||g==='easy')sess.score++;advance();}
function record(q,g){const s=item(q.id),now=Date.now();s.seen++;st.answered++;if(g==='again'){s.level=Math.max(0,s.level-1);s.ng++;s.due=now+300000}if(g==='hard'){s.ng++;s.due=now+86400000}if(g==='good'){s.level=Math.min(5,s.level+1);s.ok++;st.correct++;s.due=now+[1,2,4,8,16,30][s.level]*86400000}if(g==='easy'){s.level=Math.min(5,s.level+2);s.ok++;st.correct++;s.due=now+[2,4,8,16,30,60][s.level]*86400000}touchStreak();save();}
function advance(){sess.i++;if(sess.i<sess.queue.length)question();else finish();}
function finish(){main.innerHTML=`<section class="hero"><div class="hero-kicker">SESSION COMPLETE</div><h1>${sess.queue.length}問 完了</h1><p>正解・余裕：${sess.score}問</p><div class="hero-actions"><button class="primary-btn" id="again">もう10問</button><button class="secondary-btn" id="back">ホームへ</button></div></section>`;again.onclick=()=>start({pool:'smart',count:10,mode:sess.mode});back.onclick=()=>go('home');}
function list(){main.innerHTML=`<div class="list-toolbar"><input id="search" class="searchbox" placeholder="問題・回答を検索"><div class="filter-row"><button class="chip active" data-f="all">すべて</button><button class="chip" data-f="weak">弱点</button><button class="chip" data-f="mastered">定着</button>${cats.map(c=>`<button class="chip" data-f="${esc(c)}">${esc(c)}</button>`).join('')}</div></div><div id="rows" class="question-list"></div>`;const draw=()=>{const t=search.value.toLowerCase();let a=Q.filter(q=>(q.question+' '+q.answer).toLowerCase().includes(t));if(filter==='weak')a=a.filter(q=>(st.items[q.id]?.ng||0)>0);else if(filter==='mastered')a=a.filter(q=>(st.items[q.id]?.level||0)>=4);else if(cats.includes(filter))a=a.filter(q=>q.category===filter);rows.innerHTML=a.map(q=>`<button class="question-row" data-id="${q.id}"><strong>Q${q.id} ・ ${esc(q.category)}</strong><p>${esc(q.question)}</p></button>`).join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{sess={queue:[Q.find(q=>q.id==b.dataset.id)],i:0,mode:'recall',score:0};question()});};search.oninput=draw;document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{filter=b.dataset.f;document.querySelectorAll('[data-f]').forEach(x=>x.classList.toggle('active',x===b));draw()});draw();}
function stats(){const s=summary();main.innerHTML=`<div class="stat-grid"><div class="stat-card"><b>${st.answered||0}</b><span>総回答</span></div><div class="stat-card"><b>${s.accuracy}%</b><span>正答率</span></div><div class="stat-card"><b>${s.mastered}</b><span>定着</span></div></div><div class="section-title"><h2>分野別</h2></div><section class="panel bar-chart">${cats.map(c=>{const x=catStat(c);return`<div class="bar-row"><span>${esc(c)}</span><div class="bar"><i style="width:${x.p}%"></i></div><b>${x.p}%</b></div>`}).join('')}</section>`;}
nav.forEach(b=>b.onclick=()=>go(b.dataset.view));homeBtn.onclick=()=>go('home');settingsBtn.onclick=()=>settingsDialog.showModal();orderSetting.value=cfg.order;inputSetting.checked=cfg.showInput;largeTextSetting.checked=cfg.largeText;document.body.classList.toggle('large-text',cfg.largeText);orderSetting.onchange=()=>{cfg.order=orderSetting.value;saveCfg()};inputSetting.onchange=()=>{cfg.showInput=inputSetting.checked;saveCfg()};largeTextSetting.onchange=()=>{cfg.largeText=largeTextSetting.checked;document.body.classList.toggle('large-text',cfg.largeText);saveCfg()};resetBtn.onclick=()=>{if(confirm('学習履歴を消去しますか？')){st={items:{},answered:0,correct:0,streak:0,last:''};save();settingsDialog.close();home()}};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});go('home');
})();
