(() => {
'use strict';
function qid(){const badge=[...document.querySelectorAll('.q-meta .badge')].find(el=>/^Q\d+$/.test(el.textContent.trim()));return badge?Number(badge.textContent.trim().slice(1)):null}
function mime(data){if(data.startsWith('/9j/'))return'image/jpeg';if(data.startsWith('iVBOR'))return'image/png';if(data.startsWith('R0lGOD'))return'image/gif';if(data.startsWith('UklGR'))return'image/webp';if(data.startsWith('JVBER'))return'application/pdf';return'image/jpeg'}
function zoom(src){let dialog=document.getElementById('figureLightbox');if(!dialog){dialog=document.createElement('dialog');dialog.id='figureLightbox';dialog.className='figure-lightbox';dialog.innerHTML='<button type="button">×</button><img alt="拡大図">';document.body.appendChild(dialog);dialog.querySelector('button').onclick=()=>dialog.close();dialog.onclick=event=>{if(event.target===dialog)dialog.close()}}dialog.querySelector('img').src=src;dialog.showModal()}
async function draw(id,target){if(target.dataset.done)return;target.dataset.done='1';const session=window.AnatomyFigureSession,source=id<=121?'upper':id<=241?'lower':id<=384?'trunk':'pelvis';if(!session?.state.loaded[source]){target.innerHTML='<div class="figure-empty">設定からこの分野のGoodNotes資料を読み込んでください。</div>';return}const data=await session.dataFor(id);if(!data.length){target.innerHTML='<div class="figure-empty">元資料にこの問題専用の独立した図はありません。</div>';return}const cards=data.map((value,index)=>{const type=mime(value),url='data:'+type+';base64,'+value;return type==='application/pdf'?'<a class="figure-pdf" href="'+url+'" target="_blank" rel="noopener">PDF '+(index+1)+'</a>':'<button class="figure-button" type="button"><img src="'+url+'" alt="Q'+id+'"></button>'});target.innerHTML='<div class="figure-label">元資料の対応図</div><div class="figure-grid">'+cards.join('')+'</div>';target.querySelectorAll('.figure-button').forEach(button=>button.onclick=()=>zoom(button.querySelector('img').src))}
function render(){const answer=document.querySelector('.answer-box'),id=qid();if(!answer||!id)return;let target=answer.querySelector('.source-figure');if(!target){target=document.createElement('div');target.className='source-figure';answer.appendChild(target)}draw(id,target).catch(()=>target.innerHTML='<div class="figure-empty">図の表示に失敗しました。</div>')}
new MutationObserver(render).observe(document.documentElement,{childList:true,subtree:true});render();
})();
