window.ANATOMY_TRANSLATIONS=Object.assign(window.ANATOMY_TRANSLATIONS||{}, {
122:{en:["Iliofemoral ligament","Pubofemoral ligament","Ischiofemoral ligament","Ligament of head of femur"],la:["Ligamentum iliofemorale","Ligamentum pubofemorale","Ligamentum ischiofemorale","Ligamentum capitis femoris"]},
123:{en:["Anterior cruciate ligament","Posterior cruciate ligament","Medial collateral ligament","Lateral collateral ligament","Oblique popliteal ligament"],la:["Ligamentum cruciatum anterius","Ligamentum cruciatum posterius","Ligamentum collaterale tibiale","Ligamentum collaterale fibulare","Ligamentum popliteum obliquum"]},
124:{en:["Tibiofibular joint","Tibiofibular syndesmosis","Interosseous membrane of leg"],la:["Articulatio tibiofibularis","Syndesmosis tibiofibularis","Membrana interossea cruris"]},
125:{en:["Anterior ligament of head of fibula","Posterior ligament of head of fibula"],la:["Ligamentum capitis fibulae anterius","Ligamentum capitis fibulae posterius"]},
126:{en:["Anterior talofibular ligament","Posterior talofibular ligament","Calcaneofibular ligament","Deltoid ligament"],la:["Ligamentum talofibulare anterius","Ligamentum talofibulare posterius","Ligamentum calcaneofibulare","Ligamentum deltoideum"]},
127:{en:["Subtalar joint","Talocalcaneonavicular joint","Calcaneocuboid joint"],la:["Articulatio subtalaris","Articulatio talocalcaneonavicularis","Articulatio calcaneocuboidea"]},
128:{en:["Plantar calcaneonavicular ligament","Spring ligament"],la:["Ligamentum calcaneonaviculare plantare","Ligamentum calcaneonaviculare plantare"]},
129:{en:["Superior surface: bifurcate ligament","Inferior surface: short plantar ligament (plantar calcaneocuboid ligament)"],la:["Facies superior: ligamentum bifurcatum","Facies inferior: ligamentum calcaneocuboideum plantare"]},
130:{en:["Long plantar ligament"],la:["Ligamentum plantare longum"]},
131:{en:["Talocalcaneonavicular joint","Calcaneocuboid joint"],la:["Articulatio talocalcaneonavicularis","Articulatio calcaneocuboidea"]},
132:{en:["Calcaneus","Talus","Navicular bone","Cuneiform bones","Metatarsal bones"],la:["Calcaneus","Talus","Os naviculare","Ossa cuneiformia","Ossa metatarsalia"]},
133:{en:["Plantar talonavicular ligament","Interosseous ligaments","Plantar aponeurosis"],la:["Ligamentum talonaviculare plantare","Ligamenta interossea","Aponeurosis plantaris"]},
134:{en:["Abductor hallucis muscle","Flexor hallucis brevis muscle","Flexor digitorum brevis muscle","Tibialis anterior muscle","Flexor hallucis longus muscle","Tibialis posterior muscle"],la:["Musculus abductor hallucis","Musculus flexor hallucis brevis","Musculus flexor digitorum brevis","Musculus tibialis anterior","Musculus flexor hallucis longus","Musculus tibialis posterior"]},
135:{en:["Calcaneus","Cuboid bone","Metatarsal bones"],la:["Calcaneus","Os cuboideum","Ossa metatarsalia"]},
136:{en:["Plantar aponeurosis","Long plantar ligament","Short plantar ligament","Interosseous ligaments"],la:["Aponeurosis plantaris","Ligamentum plantare longum","Ligamentum calcaneocuboideum plantare","Ligamenta interossea"]},
137:{en:["Fibularis longus muscle","Abductor digiti minimi muscle","Flexor digitorum brevis muscle"],la:["Musculus fibularis longus","Musculus abductor digiti minimi","Musculus flexor digitorum brevis"]},
138:{en:["Cuneiform bones","Cuboid bone","Metatarsal bones"],la:["Ossa cuneiformia","Os cuboideum","Ossa metatarsalia"]},
139:{en:["Interosseous ligaments"],la:["Ligamenta interossea"]},
140:{en:["Adductor hallucis muscle","Fibularis longus muscle"],la:["Musculus adductor hallucis","Musculus fibularis longus"]},
141:{en:["Iliopsoas muscle"],la:["Musculus iliopsoas"]},
142:{en:["Iliacus muscle","Psoas major muscle","Psoas minor muscle"],la:["Musculus iliacus","Musculus psoas major","Musculus psoas minor"]},
143:{en:["Femoral nerve"],la:["Nervus femoralis"]},
144:{en:["Lateral: muscular lacuna","Medial: vascular lacuna"],la:["Lateraliter: lacuna musculorum","Medialiter: lacuna vasorum"]},
145:{en:["Iliopsoas muscle","Femoral nerve"],la:["Musculus iliopsoas","Nervus femoralis"]},
146:{en:["Femoral artery and vein","Genitofemoral nerve"],la:["Arteria et vena femorales","Nervus genitofemoralis"]},
147:{en:["Gluteus maximus muscle","Tensor fasciae latae muscle","Gluteus medius muscle","Gluteus minimus muscle"],la:["Musculus gluteus maximus","Musculus tensor fasciae latae","Musculus gluteus medius","Musculus gluteus minimus"]},
148:{en:["Piriformis muscle","Obturator internus muscle","Superior gemellus muscle","Inferior gemellus muscle","Quadratus femoris muscle","Obturator externus muscle"],la:["Musculus piriformis","Musculus obturatorius internus","Musculus gemellus superior","Musculus gemellus inferior","Musculus quadratus femoris","Musculus obturatorius externus"]},
149:{en:["Inferior gluteal nerve"],la:["Nervus gluteus inferior"]},
150:{en:["Superior gluteal nerve"],la:["Nervus gluteus superior"]},
151:{en:["Iliotibial tract"],la:["Tractus iliotibialis"]},
152:{en:["Superior gluteal nerve"],la:["Nervus gluteus superior"]},
153:{en:["Superior gluteal nerve"],la:["Nervus gluteus superior"]},
154:{en:["Superior gluteal artery and vein","Superior gluteal nerve"],la:["Arteria et vena gluteae superiores","Nervus gluteus superior"]},
155:{en:["Inferior gluteal artery and vein","Internal pudendal artery and vein","Sciatic nerve","Posterior cutaneous nerve of thigh","Inferior gluteal nerve","Pudendal nerve"],la:["Arteria et vena gluteae inferiores","Arteria et vena pudendae internae","Nervus ischiadicus","Nervus cutaneus femoris posterior","Nervus gluteus inferior","Nervus pudendus"]},
156:{en:["Obturator nerve"],la:["Nervus obturatorius"]},
157:{en:["Sartorius muscle","Quadriceps femoris muscle"],la:["Musculus sartorius","Musculus quadriceps femoris"]},
158:{en:["Femoral nerve"],la:["Nervus femoralis"]},
159:{en:["Rectus femoris muscle","Vastus lateralis muscle","Vastus intermedius muscle","Vastus medialis muscle"],la:["Musculus rectus femoris","Musculus vastus lateralis","Musculus vastus intermedius","Musculus vastus medialis"]},
160:{en:["Femoral nerve"],la:["Nervus femoralis"]},
161:{en:["Gracilis muscle","Pectineus muscle","Adductor brevis muscle","Adductor longus muscle","Adductor magnus muscle"],la:["Musculus gracilis","Musculus pectineus","Musculus adductor brevis","Musculus adductor longus","Musculus adductor magnus"]},
162:{en:["Obturator nerve"],la:["Nervus obturatorius"]},
163:{en:["Femoral nerve"],la:["Nervus femoralis"]},
164:{en:["Obturator nerve"],la:["Nervus obturatorius"]},
165:{en:["Obturator nerve"],la:["Nervus obturatorius"]},
166:{en:["Obturator nerve"],la:["Nervus obturatorius"]},
167:{en:["Superior: inguinal ligament","Lateral: medial border of sartorius muscle","Medial: lateral border of adductor longus muscle"],la:["Superior: ligamentum inguinale","Lateraliter: margo medialis musculi sartorii","Medialiter: margo lateralis musculi adductoris longi"]},
168:{en:["Femoral artery and vein","Femoral nerve","Deep inguinal lymph nodes"],la:["Arteria et vena femorales","Nervus femoralis","Nodi lymphoidei inguinales profundi"]},
169:{en:["Anterior: anteromedial intermuscular septum of thigh","Lateral: vastus medialis muscle","Medial and posterior: adductor magnus muscle"],la:["Anterior: septum intermusculare femoris anteromediale","Lateraliter: musculus vastus medialis","Medialiter et posterior: musculus adductor magnus"]},
170:{en:["Biceps femoris muscle","Semitendinosus muscle","Semimembranosus muscle"],la:["Musculus biceps femoris","Musculus semitendinosus","Musculus semimembranosus"]},
171:{en:["Long head: tibial nerve","Short head: common fibular nerve"],la:["Caput longum: nervus tibialis","Caput breve: nervus fibularis communis"]},
172:{en:["Tibial nerve"],la:["Nervus tibialis"]},
173:{en:["Tibial nerve"],la:["Nervus tibialis"]},
174:{en:["Sartorius muscle","Gracilis muscle","Semitendinosus muscle"],la:["Musculus sartorius","Musculus gracilis","Musculus semitendinosus"]},
175:{en:["Tendon of biceps femoris muscle"],la:["Tendo musculi bicipitis femoris"]},
176:{en:["Tendon of semitendinosus muscle","Tendon of semimembranosus muscle"],la:["Tendo musculi semitendinosi","Tendo musculi semimembranosi"]},
177:{en:["Gastrocnemius muscle"],la:["Musculus gastrocnemius"]},
178:{en:["Common fibular nerve","Tibial nerve","Posterior cutaneous nerve of thigh"],la:["Nervus fibularis communis","Nervus tibialis","Nervus cutaneus femoris posterior"]},
179:{en:["Saphenous opening"],la:["Hiatus saphenus"]},
180:{en:["Tibialis anterior muscle","Fibularis tertius muscle","Extensor hallucis longus muscle","Extensor digitorum longus muscle","Extensor digitorum brevis muscle"],la:["Musculus tibialis anterior","Musculus fibularis tertius","Musculus extensor hallucis longus","Musculus extensor digitorum longus","Musculus extensor digitorum brevis"]},
181:{en:["Deep fibular nerve"],la:["Nervus fibularis profundus"]},
182:{en:["Deep fibular nerve"],la:["Nervus fibularis profundus"]},
183:{en:["Deep fibular nerve"],la:["Nervus fibularis profundus"]},
184:{en:["Deep fibular nerve"],la:["Nervus fibularis profundus"]},
185:{en:["Deep fibular nerve"],la:["Nervus fibularis profundus"]},
186:{en:["Fibularis longus muscle","Fibularis brevis muscle"],la:["Musculus fibularis longus","Musculus fibularis brevis"]},
187:{en:["Superficial fibular nerve"],la:["Nervus fibularis superficialis"]},
188:{en:["Superficial fibular nerve"],la:["Nervus fibularis superficialis"]},
189:{en:["Triceps surae muscle","Popliteus muscle"],la:["Musculus triceps surae","Musculus popliteus"]},
190:{en:["Gastrocnemius muscle","Soleus muscle","Plantaris muscle"],la:["Musculus gastrocnemius","Musculus soleus","Musculus plantaris"]},
191:{en:["Tibial nerve"],la:["Nervus tibialis"]},
192:{en:["Tibial nerve"],la:["Nervus tibialis"]},
193:{en:["Flexor hallucis longus muscle","Flexor digitorum longus muscle","Tibialis posterior muscle"],la:["Musculus flexor hallucis longus","Musculus flexor digitorum longus","Musculus tibialis posterior"]},
194:{en:["Tibial nerve"],la:["Nervus tibialis"]},
195:{en:["Tibial nerve"],la:["Nervus tibialis"]},
196:{en:["Tibial nerve"],la:["Nervus tibialis"]},
197:{en:["Anterior intermuscular septum of leg"],la:["Septum intermusculare cruris anterius"]},
198:{en:["Posterior intermuscular septum of leg"],la:["Septum intermusculare cruris posterius"]},
199:{en:["Superior extensor retinaculum","Inferior extensor retinaculum"],la:["Retinaculum musculorum extensorum superius","Retinaculum musculorum extensorum inferius"]},
200:{en:["Superior fibular retinaculum","Inferior fibular retinaculum"],la:["Retinaculum musculorum fibularium superius","Retinaculum musculorum fibularium inferius"]},
201:{en:["Flexor retinaculum"],la:["Retinaculum musculorum flexorum"]},
202:{en:["Tibialis posterior muscle","Flexor digitorum longus muscle","Flexor hallucis longus muscle"],la:["Musculus tibialis posterior","Musculus flexor digitorum longus","Musculus flexor hallucis longus"]},
203:{en:["Abductor hallucis muscle","Flexor digitorum brevis muscle","Abductor digiti minimi muscle"],la:["Musculus abductor hallucis","Musculus flexor digitorum brevis","Musculus abductor digiti minimi"]},
204:{en:["Medial plantar nerve"],la:["Nervus plantaris medialis"]},
205:{en:["Medial plantar nerve"],la:["Nervus plantaris medialis"]},
206:{en:["Lateral plantar nerve"],la:["Nervus plantaris lateralis"]},
207:{en:["Quadratus plantae muscle","Lumbrical muscles"],la:["Musculus quadratus plantae","Musculi lumbricales"]},
208:{en:["Lateral plantar nerve"],la:["Nervus plantaris lateralis"]},
209:{en:["Flexor hallucis brevis muscle","Adductor hallucis muscle","Flexor digiti minimi brevis muscle"],la:["Musculus flexor hallucis brevis","Musculus adductor hallucis","Musculus flexor digiti minimi brevis"]},
210:{en:["Medial plantar nerve"],la:["Nervus plantaris medialis"]},
211:{en:["Medial plantar nerve","Lateral plantar nerve"],la:["Nervus plantaris medialis","Nervus plantaris lateralis"]},
212:{en:["Lateral plantar nerve"],la:["Nervus plantaris lateralis"]},
213:{en:["Dorsal interosseous muscles","Plantar interosseous muscles","Opponens digiti minimi muscle"],la:["Musculi interossei dorsales","Musculi interossei plantares","Musculus opponens digiti minimi"]},
214:{en:["Lateral plantar nerve"],la:["Nervus plantaris lateralis"]},
215:{en:["Lateral plantar nerve"],la:["Nervus plantaris lateralis"]},
216:{en:["Lateral plantar nerve"],la:["Nervus plantaris lateralis"]},
217:{en:["Iliopsoas muscle","Rectus femoris muscle","Tensor fasciae latae muscle","Gluteus medius muscle","Gluteus minimus muscle"],la:["Musculus iliopsoas","Musculus rectus femoris","Musculus tensor fasciae latae","Musculus gluteus medius","Musculus gluteus minimus"]},
218:{en:["Gluteus maximus muscle","Adductor magnus muscle","Semimembranosus muscle","Gluteus medius muscle"],la:["Musculus gluteus maximus","Musculus adductor magnus","Musculus semimembranosus","Musculus gluteus medius"]},
219:{en:["Gluteus medius muscle","Gluteus minimus muscle","Tensor fasciae latae muscle","Gluteus maximus muscle","Rectus femoris muscle"],la:["Musculus gluteus medius","Musculus gluteus minimus","Musculus tensor fasciae latae","Musculus gluteus maximus","Musculus rectus femoris"]},
220:{en:["Adductor magnus muscle","Adductor longus muscle","Pectineus muscle","Semimembranosus muscle","Iliopsoas muscle"],la:["Musculus adductor magnus","Musculus adductor longus","Musculus pectineus","Musculus semimembranosus","Musculus iliopsoas"]},
221:{en:["Adductor magnus muscle","Adductor longus muscle","Gluteus medius muscle","Gluteus minimus muscle","Tensor fasciae latae muscle"],la:["Musculus adductor magnus","Musculus adductor longus","Musculus gluteus medius","Musculus gluteus minimus","Musculus tensor fasciae latae"]},
222:{en:["Semimembranosus muscle","Semitendinosus muscle","Biceps femoris muscle","Gracilis muscle","Sartorius muscle"],la:["Musculus semimembranosus","Musculus semitendinosus","Musculus biceps femoris","Musculus gracilis","Musculus sartorius"]},
223:{en:["Quadriceps femoris muscle","Tensor fasciae latae muscle"],la:["Musculus quadriceps femoris","Musculus tensor fasciae latae"]},
224:{en:["Semimembranosus muscle","Popliteus muscle","Semitendinosus muscle","Gracilis muscle","Sartorius muscle"],la:["Musculus semimembranosus","Musculus popliteus","Musculus semitendinosus","Musculus gracilis","Musculus sartorius"]},
225:{en:["Biceps femoris muscle","Tensor fasciae latae muscle"],la:["Musculus biceps femoris","Musculus tensor fasciae latae"]},
226:{en:["Tibialis anterior muscle","Extensor digitorum longus muscle","Fibularis tertius muscle","Extensor hallucis longus muscle"],la:["Musculus tibialis anterior","Musculus extensor digitorum longus","Musculus fibularis tertius","Musculus extensor hallucis longus"]},
227:{en:["Gastrocnemius muscle","Soleus muscle","Flexor hallucis longus muscle","Tibialis posterior muscle","Flexor digitorum longus muscle","Fibularis longus muscle"],la:["Musculus gastrocnemius","Musculus soleus","Musculus flexor hallucis longus","Musculus tibialis posterior","Musculus flexor digitorum longus","Musculus fibularis longus"]},
228:{en:["Tibialis posterior muscle","Tibialis anterior muscle","Flexor digitorum longus muscle","Flexor hallucis longus muscle"],la:["Musculus tibialis posterior","Musculus tibialis anterior","Musculus flexor digitorum longus","Musculus flexor hallucis longus"]},
229:{en:["Fibularis longus muscle","Fibularis brevis muscle","Extensor digitorum longus muscle","Fibularis tertius muscle"],la:["Musculus fibularis longus","Musculus fibularis brevis","Musculus extensor digitorum longus","Musculus fibularis tertius"]},
230:{en:["Superficial epigastric artery","Superficial circumflex iliac artery","External pudendal arteries","Deep artery of thigh","Descending genicular artery"],la:["Arteria epigastrica superficialis","Arteria circumflexa ilium superficialis","Arteriae pudendae externae","Arteria profunda femoris","Arteria genus descendens"]},
231:{en:["Medial circumflex femoral artery","Lateral circumflex femoral artery","Perforating arteries"],la:["Arteria circumflexa femoris medialis","Arteria circumflexa femoris lateralis","Arteriae perforantes"]},
232:{en:["Fibular artery","Medial plantar artery","Lateral plantar artery"],la:["Arteria fibularis","Arteria plantaris medialis","Arteria plantaris lateralis"]},
233:{en:["Great saphenous vein","Small saphenous vein"],la:["Vena saphena magna","Vena saphena parva"]},
234:{en:["Femoral vein","Popliteal vein","Anterior tibial veins","Posterior tibial veins"],la:["Vena femoralis","Vena poplitea","Venae tibiales anteriores","Venae tibiales posteriores"]},
235:{en:["Superficial inguinal lymph nodes","Superficial popliteal lymph nodes"],la:["Nodi lymphoidei inguinales superficiales","Nodi lymphoidei poplitei superficiales"]},
236:{en:["Deep inguinal lymph nodes","Anterior tibial lymph nodes","Deep popliteal lymph nodes"],la:["Nodi lymphoidei inguinales profundi","Nodi lymphoidei tibiales anteriores","Nodi lymphoidei poplitei profundi"]},
237:{en:["Iliohypogastric nerve","Ilioinguinal nerve","Genitofemoral nerve","Lateral cutaneous nerve of thigh","Femoral nerve","Obturator nerve"],la:["Nervus iliohypogastricus","Nervus ilioinguinalis","Nervus genitofemoralis","Nervus cutaneus femoris lateralis","Nervus femoralis","Nervus obturatorius"]},
238:{en:["Superior gluteal nerve","Inferior gluteal nerve","Posterior cutaneous nerve of thigh","Sciatic nerve"],la:["Nervus gluteus superior","Nervus gluteus inferior","Nervus cutaneus femoris posterior","Nervus ischiadicus"]},
239:{en:["Common fibular nerve","Tibial nerve"],la:["Nervus fibularis communis","Nervus tibialis"]},
240:{en:["Lateral sural cutaneous nerve","Superficial fibular nerve","Deep fibular nerve"],la:["Nervus cutaneus surae lateralis","Nervus fibularis superficialis","Nervus fibularis profundus"]},
241:{en:["Medial plantar nerve","Lateral plantar nerve"],la:["Nervus plantaris medialis","Nervus plantaris lateralis"]}
});
