window.ANATOMY_TRANSLATIONS=Object.assign(window.ANATOMY_TRANSLATIONS||{}, {
385:{en:["Superior pubic ligament","Arcuate pubic ligament"],la:["Ligamentum pubicum superius","Ligamentum arcuatum pubis"]},
386:{en:["Interosseous sacroiliac ligament","Anterior sacroiliac ligament","Posterior sacroiliac ligament"],la:["Ligamentum sacroiliacum interosseum","Ligamentum sacroiliacum anterius","Ligamentum sacroiliacum posterius"]},
387:{en:["Sacrotuberous ligament","Sacrospinous ligament"],la:["Ligamentum sacrotuberale","Ligamentum sacrospinale"]},
388:{en:["Sacrospinous ligament","Greater sciatic notch"],la:["Ligamentum sacrospinale","Incisura ischiadica major"]},
389:{en:["Lesser sciatic notch","Sacrospinous ligament","Sacrotuberous ligament"],la:["Incisura ischiadica minor","Ligamentum sacrospinale","Ligamentum sacrotuberale"]},
390:{en:["Tendon of obturator internus muscle","Internal pudendal artery and vein","Pudendal nerve"],la:["Tendo musculi obturatorii interni","Arteria et vena pudendae internae","Nervus pudendus"]},
391:{en:["Rectovesical pouch"],la:["Excavatio rectovesicalis"]},
392:{en:["Vesicouterine pouch"],la:["Excavatio vesicouterina"]},
393:{en:["Pubovesical ligament","Medial puboprostatic ligament","Female: medial pubovesical ligament"],la:["Ligamentum pubovesicale","Ligamentum puboprostaticum mediale","In femina: ligamentum pubovesicale mediale"]},
394:{en:["Superior rectal artery ← inferior mesenteric artery","Middle rectal artery ← internal iliac artery","Inferior rectal artery ← internal pudendal artery"],la:["Arteria rectalis superior ← arteria mesenterica inferior","Arteria rectalis media ← arteria iliaca interna","Arteria rectalis inferior ← arteria pudenda interna"]},
395:{en:["Superior rectal vein → inferior mesenteric vein","Middle rectal vein → internal iliac vein","Inferior rectal vein → internal iliac vein"],la:["Vena rectalis superior → vena mesenterica inferior","Vena rectalis media → vena iliaca interna","Vena rectalis inferior → vena iliaca interna"]},
396:{en:["Inferior mesenteric lymph nodes"],la:["Nodi lymphoidei mesenterici inferiores"]},
397:{en:["Sacral lymph nodes","Internal iliac lymph nodes","Common iliac lymph nodes"],la:["Nodi lymphoidei sacrales","Nodi lymphoidei iliaci interni","Nodi lymphoidei iliaci communes"]},
398:{en:["Superficial inguinal lymph nodes"],la:["Nodi lymphoidei inguinales superficiales"]},
399:{en:["Testis","Epididymis","Ductus deferens","Seminal gland (seminal vesicle)","Prostate","Penis"],la:["Testis","Epididymis","Ductus deferens","Glandula vesiculosa","Prostata","Penis"]},
400:{en:["Appendix testis: remnant of paramesonephric (Müllerian) duct","Appendix epididymis: remnant of mesonephric (Wolffian) duct","Paradidymis: remnant of mesonephric duct"],la:["Appendix testis: reliquiae ductus paramesonephrici","Appendix epididymidis: reliquiae ductus mesonephrici","Paradidymis: reliquiae ductus mesonephrici"]},
401:{en:["Ductus deferens","Testicular artery","Pampiniform venous plexus","Lymphatic vessels","Nerves"],la:["Ductus deferens","Arteria testicularis","Plexus venosus pampiniformis","Vasa lymphatica","Nervi"]},
402:{en:["External spermatic fascia","Cremasteric fascia","Internal spermatic fascia","Tunica vaginalis of testis"],la:["Fascia spermatica externa","Fascia cremasterica","Fascia spermatica interna","Tunica vaginalis testis"]},
403:{en:["Ovary","Uterine tube","Uterus","Vagina"],la:["Ovarium","Tuba uterina","Uterus","Vagina"]},
404:{en:["Superior: external iliac artery and vein","Posterior: internal iliac artery and vein, ureter","Floor: obturator nerve"],la:["Superior: arteria et vena iliacae externae","Posterior: arteria et vena iliacae internae, ureter","Fundus: nervus obturatorius"]},
405:{en:["Suspensory ligament of ovary","Proper ligament of ovary"],la:["Ligamentum suspensorium ovarii","Ligamentum ovarii proprium"]},
406:{en:["Epoophoron: remnant of mesonephric (Wolffian) duct","Paroophoron: remnant of caudal mesonephric tubules","Gartner duct: remnant of mesonephric duct"],la:["Epoophoron: reliquiae ductus mesonephrici","Paroophoron: reliquiae tubulorum mesonephricorum caudalium","Ductus Gartneri: reliquiae ductus mesonephrici"]},
407:{en:["Levator ani muscle","Pubocervical ligament","Transverse cervical ligament (cardinal ligament)","Uterosacral ligament","Round ligament of uterus"],la:["Musculus levator ani","Ligamentum pubocervicale","Ligamentum transversum cervicis (ligamentum cardinale)","Ligamentum sacrouterinum","Ligamentum teres uteri"]},
408:{en:["Fundus of uterus: lumbar lymph nodes","Body of uterus: external iliac lymph nodes","Cervix of uterus: external iliac, internal iliac, and sacral lymph nodes"],la:["Fundus uteri: nodi lymphoidei lumbales","Corpus uteri: nodi lymphoidei iliaci externi","Cervix uteri: nodi lymphoidei iliaci externi, iliaci interni et sacrales"]},
409:{en:["Urethra","Anal canal","Vagina (female only)"],la:["Urethra","Canalis analis","Vagina (in femina)"]},
410:{en:["Levator ani muscle","Coccygeus muscle","Superior fascia of pelvic diaphragm","Inferior fascia of pelvic diaphragm"],la:["Musculus levator ani","Musculus coccygeus","Fascia diaphragmatis pelvis superior","Fascia diaphragmatis pelvis inferior"]},
411:{en:["Iliococcygeus muscle","Pubococcygeus muscle","Puborectalis muscle"],la:["Musculus iliococcygeus","Musculus pubococcygeus","Musculus puborectalis"]},
412:{en:["Male: puboprostatic ligaments","Female: pubovesical ligament, transverse cervical ligament, uterosacral ligament"],la:["In viro: ligamenta puboprostatica","In femina: ligamentum pubovesicale, ligamentum transversum cervicis, ligamentum sacrouterinum"]},
413:{en:["Male: crura of penis at root of penis, bulb of penis","Female: crura of clitoris, bulbs of vestibule, greater vestibular glands"],la:["In viro: crura penis ad radicem penis, bulbus penis","In femina: crura clitoridis, bulbi vestibuli, glandulae vestibulares majores"]},
414:{en:["External urethral sphincter muscle","Bulbourethral gland (Cowper gland)"],la:["Musculus sphincter urethrae externus","Glandula bulbourethralis"]},
415:{en:["Apex: coccyx","Sides: sacrotuberous ligaments","Base: line joining the ischial tuberosities"],la:["Apex: os coccygis","Latera: ligamenta sacrotuberalia","Basis: linea inter tubera ischiadica"]},
416:{en:["Root of penis","Body of penis","Glans penis","Fundiform ligament of penis","Suspensory ligament of penis"],la:["Radix penis","Corpus penis","Glans penis","Ligamentum fundiforme penis","Ligamentum suspensorium penis"]},
417:{en:["Corpora cavernosa of penis","Corpus spongiosum of penis"],la:["Corpora cavernosa penis","Corpus spongiosum penis"]},
418:{en:["Ischiocavernosus muscle","Bulbospongiosus muscle"],la:["Musculus ischiocavernosus","Musculus bulbospongiosus"]},
419:{en:["Iliolumbar artery","Lateral sacral arteries","Superior gluteal artery","Inferior gluteal artery","Obturator artery","Internal pudendal artery"],la:["Arteria iliolumbalis","Arteriae sacrales laterales","Arteria glutea superior","Arteria glutea inferior","Arteria obturatoria","Arteria pudenda interna"]},
420:{en:["Inferior rectal artery","Perineal artery","Artery of bulb of penis (or bulb of vestibule)","Urethral artery","Deep artery of penis (or clitoris)","Dorsal artery of penis (or clitoris)"],la:["Arteria rectalis inferior","Arteria perinealis","Arteria bulbi penis (vel arteria bulbi vestibuli)","Arteria urethralis","Arteria profunda penis (vel arteria profunda clitoridis)","Arteria dorsalis penis (vel arteria dorsalis clitoridis)"]},
421:{en:["Umbilical artery","Inferior vesical artery","Middle rectal artery","Uterine artery (female only)"],la:["Arteria umbilicalis","Arteria vesicalis inferior","Arteria rectalis media","Arteria uterina (in femina)"]},
422:{en:["Superior vesical arteries","Artery to ductus deferens"],la:["Arteriae vesicales superiores","Arteria ductus deferentis"]},
423:{en:["Internal iliac lymph nodes","Sacral lymph nodes","External iliac lymph nodes","Common iliac lymph nodes"],la:["Nodi lymphoidei iliaci interni","Nodi lymphoidei sacrales","Nodi lymphoidei iliaci externi","Nodi lymphoidei iliaci communes"]},
424:{en:["Sciatic nerve","Superior gluteal nerve","Inferior gluteal nerve","Posterior cutaneous nerve of thigh"],la:["Nervus ischiadicus","Nervus gluteus superior","Nervus gluteus inferior","Nervus cutaneus femoris posterior"]},
425:{en:["Pudendal nerve","Pelvic splanchnic nerves","Erectile nerves"],la:["Nervus pudendus","Nervi splanchnici pelvici","Nervi erigentes"]},
426:{en:["Inferior rectal nerve","Perineal nerve","Dorsal nerve of penis (or clitoris)"],la:["Nervus rectalis inferior","Nervus perinealis","Nervus dorsalis penis (vel nervus dorsalis clitoridis)"]}
});
