window.ANATOMY_TRANSLATIONS=Object.assign(window.ANATOMY_TRANSLATIONS||{}, {
511:{en:["I: olfactory nerve — foramina of cribriform plate; II: optic nerve — optic canal","III: oculomotor nerve — superior orbital fissure; IV: trochlear nerve — superior orbital fissure","V: trigeminal nerve — superior orbital fissure, foramen rotundum, and foramen ovale","VI: abducens nerve — superior orbital fissure","VII: facial nerve — internal acoustic meatus; VIII: vestibulocochlear nerve — internal acoustic meatus","IX: glossopharyngeal nerve — jugular foramen; X: vagus nerve — jugular foramen; XI: accessory nerve — jugular foramen; XII: hypoglossal nerve — hypoglossal canal"],la:["I: nervus olfactorius — foramina cribrosa laminae cribrosae; II: nervus opticus — canalis opticus","III: nervus oculomotorius — fissura orbitalis superior; IV: nervus trochlearis — fissura orbitalis superior","V: nervus trigeminus — fissura orbitalis superior, foramen rotundum et foramen ovale","VI: nervus abducens — fissura orbitalis superior","VII: nervus facialis — meatus acusticus internus; VIII: nervus vestibulocochlearis — meatus acusticus internus","IX: nervus glossopharyngeus — foramen jugulare; X: nervus vagus — foramen jugulare; XI: nervus accessorius — foramen jugulare; XII: nervus hypoglossus — canalis nervi hypoglossi"]},
512:{en:["Ophthalmic artery","Anterior cerebral artery","Middle cerebral artery","Anterior choroidal artery","Posterior communicating artery"],la:["Arteria ophthalmica","Arteria cerebri anterior","Arteria cerebri media","Arteria choroidea anterior","Arteria communicans posterior"]},
513:{en:["Meningeal branch","Posterior spinal artery","Anterior spinal artery","Median medullary branches","Posterior inferior cerebellar artery"],la:["Ramus meningeus","Arteria spinalis posterior","Arteria spinalis anterior","Rami medullares mediani","Arteria cerebelli inferior posterior"]},
514:{en:["Anterior inferior cerebellar artery","Labyrinthine artery","Pontine branches","Superior cerebellar artery","Posterior cerebral artery"],la:["Arteria cerebelli inferior anterior","Arteria labyrinthi","Rami pontini","Arteria cerebelli superior","Arteria cerebri posterior"]},
515:{en:["Anterior communicating artery","Anterior cerebral arteries","Middle cerebral arteries","Internal carotid arteries","Posterior communicating arteries","Posterior cerebral arteries"],la:["Arteria communicans anterior","Arteriae cerebri anteriores","Arteriae cerebri mediae","Arteriae carotides internae","Arteriae communicantes posteriores","Arteriae cerebri posteriores"]},
516:{en:["Superior cerebral veins","Superficial middle cerebral vein","Inferior cerebral veins"],la:["Venae cerebri superiores","Vena media superficialis cerebri","Venae cerebri inferiores"]},
517:{en:["Basal vein (vein of Rosenthal)","Internal cerebral veins","Great cerebral vein (vein of Galen)"],la:["Vena basalis (vena Rosenthali)","Venae internae cerebri","Vena magna cerebri (vena Galeni)"]},
518:{en:["Anterior cerebral vein","Deep middle cerebral vein"],la:["Vena anterior cerebri","Vena media profunda cerebri"]},
519:{en:["Vein of septum pellucidum","Superior thalamostriate vein","Superior choroidal vein"],la:["Vena septi pellucidi","Vena thalamostriata superior","Vena choroidea superior"]},
520:{en:["Superior and inferior sagittal sinuses","Straight sinus and occipital sinus","Sigmoid sinus and transverse sinus","Cavernous sinus and sphenoparietal sinus","Superior and inferior petrosal sinuses"],la:["Sinus sagittalis superior et sinus sagittalis inferior","Sinus rectus et sinus occipitalis","Sinus sigmoideus et sinus transversus","Sinus cavernosus et sinus sphenoparietalis","Sinus petrosus superior et sinus petrosus inferior"]}
});
