window.ANATOMY_TRANSLATIONS=Object.assign(window.ANATOMY_TRANSLATIONS||{}, {
242:{en:["Central part: nucleus pulposus","Peripheral part: anulus fibrosus"],la:["Pars centralis: nucleus pulposus","Pars peripherica: anulus fibrosus"]},
243:{en:["Anterior longitudinal ligament","Posterior longitudinal ligament"],la:["Ligamentum longitudinale anterius","Ligamentum longitudinale posterius"]},
244:{en:["Ligamenta flava","Interspinous ligaments","Supraspinous ligament"],la:["Ligamenta flava","Ligamenta interspinalia","Ligamentum supraspinale"]},
245:{en:["Atlanto-occipital joint","Atlanto-axial joints"],la:["Articulatio atlantooccipitalis","Articulationes atlantoaxiales"]},
246:{en:["Median atlanto-axial joint","Lateral atlanto-axial joints"],la:["Articulatio atlantoaxialis mediana","Articulationes atlantoaxiales laterales"]},
247:{en:["Tectorial membrane","Cruciform ligament of atlas","Alar ligaments","Apical ligament of dens"],la:["Membrana tectoria","Ligamentum cruciforme atlantis","Ligamenta alaria","Ligamentum apicis dentis"]},
248:{en:["Transverse ligament of atlas","Longitudinal bands"],la:["Ligamentum transversum atlantis","Fasciculi longitudinales"]},
249:{en:["Trapezius muscle","Latissimus dorsi muscle","Levator scapulae muscle","Rhomboid muscles"],la:["Musculus trapezius","Musculus latissimus dorsi","Musculus levator scapulae","Musculi rhomboidei"]},
250:{en:["Serratus posterior superior muscle","Serratus posterior inferior muscle"],la:["Musculus serratus posterior superior","Musculus serratus posterior inferior"]},
251:{en:["Splenius muscles","Erector spinae muscle"],la:["Musculi splenii","Musculus erector spinae"]},
252:{en:["Iliocostalis muscle","Longissimus muscle","Spinalis muscle"],la:["Musculus iliocostalis","Musculus longissimus","Musculus spinalis"]},
253:{en:["Semispinalis muscle","Multifidus muscle","Rotatores muscles","Interspinales muscles","Intertransversarii muscles"],la:["Musculus semispinalis","Musculus multifidus","Musculi rotatores","Musculi interspinales","Musculi intertransversarii"]},
254:{en:["Rectus capitis posterior major muscle","Rectus capitis posterior minor muscle","Obliquus capitis superior muscle","Obliquus capitis inferior muscle"],la:["Musculus rectus capitis posterior major","Musculus rectus capitis posterior minor","Musculus obliquus capitis superior","Musculus obliquus capitis inferior"]},
255:{en:["Rectus capitis posterior major muscle","Obliquus capitis superior muscle","Obliquus capitis inferior muscle"],la:["Musculus rectus capitis posterior major","Musculus obliquus capitis superior","Musculus obliquus capitis inferior"]},
256:{en:["Vertebral artery","Suboccipital nerve"],la:["Arteria vertebralis","Nervus suboccipitalis"]},
257:{en:["Costovertebral joints","Sternocostal joints"],la:["Articulationes costovertebrales","Articulationes sternocostales"]},
258:{en:["Joint of head of rib","Costotransverse joint"],la:["Articulatio capitis costae","Articulatio costotransversaria"]},
259:{en:["Radiate ligament of head of rib","Superior costotransverse ligament","Lateral costotransverse ligament"],la:["Ligamentum capitis costae radiatum","Ligamentum costotransversarium superius","Ligamentum costotransversarium laterale"]},
260:{en:["First thoracic vertebra","First rib","Manubrium of sternum"],la:["Vertebra thoracica prima","Costa prima","Manubrium sterni"]},
261:{en:["Twelfth thoracic vertebra","Twelfth rib","Costal arch","Inferior end of sternum (xiphoid process)"],la:["Vertebra thoracica duodecima","Costa duodecima","Arcus costalis","Extremitas inferior sterni (processus xiphoideus)"]},
262:{en:["External intercostal muscles","Internal intercostal muscles","Innermost intercostal muscles","Subcostal muscles","Transversus thoracis muscle","Levatores costarum muscles","Serratus posterior superior muscle","Serratus posterior inferior muscle"],la:["Musculi intercostales externi","Musculi intercostales interni","Musculi intercostales intimi","Musculi subcostales","Musculus transversus thoracis","Musculi levatores costarum","Musculus serratus posterior superior","Musculus serratus posterior inferior"]},
263:{en:["Intercostal nerves"],la:["Nervi intercostales"]},
264:{en:["Intercostal nerves"],la:["Nervi intercostales"]},
265:{en:["Intercostal nerves"],la:["Nervi intercostales"]},
266:{en:["Intercostal nerves"],la:["Nervi intercostales"]},
267:{en:["Intercostal nerves"],la:["Nervi intercostales"]},
268:{en:["Intercostal nerves"],la:["Nervi intercostales"]},
269:{en:["Intercostal nerves"],la:["Nervi intercostales"]},
270:{en:["Medial arcuate ligament","Lateral arcuate ligament"],la:["Ligamentum arcuatum mediale","Ligamentum arcuatum laterale"]},
271:{en:["Sternocostal triangle"],la:["Trigonum sternocostale"]},
272:{en:["Lumbocostal triangle"],la:["Trigonum lumbocostale"]},
273:{en:["Aortic hiatus","Esophageal hiatus","Caval opening"],la:["Hiatus aorticus","Hiatus oesophageus","Foramen venae cavae"]},
274:{en:["Aorta","Thoracic duct","Azygos vein"],la:["Aorta","Ductus thoracicus","Vena azygos"]},
275:{en:["Esophagus","Branches of left gastric artery","Vagus nerve","Branches of left phrenic nerve"],la:["Oesophagus","Rami arteriae gastricae sinistrae","Nervus vagus","Rami nervi phrenici sinistri"]},
276:{en:["Inferior vena cava","Branches of right phrenic nerve"],la:["Vena cava inferior","Rami nervi phrenici dextri"]},
277:{en:["Anterior intercostal branches","Superior epigastric artery","Musculophrenic artery"],la:["Rami intercostales anteriores","Arteria epigastrica superior","Arteria musculophrenica"]},
278:{en:["Supreme intercostal artery"],la:["Arteria intercostalis suprema"]},
279:{en:["Thoracic aorta"],la:["Aorta thoracica"]},
280:{en:["Axillary lymph nodes"],la:["Nodi lymphoidei axillares"]},
281:{en:["Parasternal lymph nodes","Intercostal lymph nodes","Diaphragmatic lymph nodes"],la:["Nodi lymphoidei parasternales","Nodi lymphoidei intercostales","Nodi lymphoidei phrenici"]},
282:{en:["Internal thoracic artery","Lateral thoracic artery","Thoracoacromial artery"],la:["Arteria thoracica interna","Arteria thoracica lateralis","Arteria thoracoacromialis"]},
283:{en:["Internal thoracic veins","Lateral thoracic vein","Intercostal veins"],la:["Venae thoracicae internae","Vena thoracica lateralis","Venae intercostales"]},
284:{en:["Axillary lymph nodes","Parasternal lymph nodes","Intercostal lymph nodes"],la:["Nodi lymphoidei axillares","Nodi lymphoidei parasternales","Nodi lymphoidei intercostales"]},
285:{en:["Inferior thyroid artery"],la:["Arteria thyroidea inferior"]},
286:{en:["Inferior thyroid veins"],la:["Venae thyroideae inferiores"]},
287:{en:["Tracheobronchial lymph nodes","Paratracheal lymph nodes"],la:["Nodi lymphoidei tracheobronchiales","Nodi lymphoidei paratracheales"]},
288:{en:["Inferior laryngeal nerve","Sympathetic nerves"],la:["Nervus laryngeus inferior","Nervi sympathici"]},
289:{en:["Bronchopulmonary lymph nodes","Tracheobronchial lymph nodes"],la:["Nodi lymphoidei bronchopulmonales","Nodi lymphoidei tracheobronchiales"]},
290:{en:["Functional artery: pulmonary artery","Nutrient artery: bronchial artery"],la:["Arteria functionalis: arteria pulmonalis","Arteria nutricia: arteria bronchialis"]},
291:{en:["Visceral pleura (pulmonary pleura)","Parietal pleura"],la:["Pleura visceralis (pleura pulmonalis)","Pleura parietalis"]},
292:{en:["Costal pleura","Mediastinal pleura","Diaphragmatic pleura"],la:["Pleura costalis","Pleura mediastinalis","Pleura diaphragmatica"]},
293:{en:["Endothoracic fascia"],la:["Fascia endothoracica"]},
294:{en:["Costomediastinal recess","Costodiaphragmatic recess"],la:["Recessus costomediastinalis","Recessus costodiaphragmaticus"]},
295:{en:["Upper third: inferior thyroid artery","Middle third: esophageal arteries","Lower third: left gastric artery"],la:["Tertia superior: arteria thyroidea inferior","Tertia media: arteriae oesophageales","Tertia inferior: arteria gastrica sinistra"]},
296:{en:["Upper part: inferior thyroid veins","Middle part: azygos and hemiazygos veins","Lower part: left gastric vein"],la:["Pars superior: venae thyroideae inferiores","Pars media: vena azygos et vena hemiazygos","Pars inferior: vena gastrica sinistra"]},
297:{en:["Upper part: deep cervical lymph nodes","Middle part: supraclavicular lymph nodes","Lower part: celiac lymph nodes"],la:["Pars superior: nodi lymphoidei cervicales profundi","Pars media: nodi lymphoidei supraclaviculares","Pars inferior: nodi lymphoidei coeliaci"]},
298:{en:["Coronary sulcus"],la:["Sulcus coronarius"]},
299:{en:["Anterior interventricular sulcus","Posterior interventricular sulcus"],la:["Sulcus interventricularis anterior","Sulcus interventricularis posterior"]},
300:{en:["Endocardium","Myocardium","Epicardium"],la:["Endocardium","Myocardium","Epicardium"]},
301:{en:["Posterior interventricular branch (posterior descending branch)","Right marginal branch (acute marginal branch)"],la:["Ramus interventricularis posterior","Ramus marginalis dexter"]},
302:{en:["Anterior interventricular branch (descending branch)","Circumflex branch"],la:["Ramus interventricularis anterior","Ramus circumflexus"]},
303:{en:["Great cardiac vein","Middle cardiac vein","Small cardiac vein","Posterior vein of left ventricle","Posterior vein of left atrium"],la:["Vena cardiaca magna","Vena cardiaca media","Vena cardiaca parva","Vena posterior ventriculi sinistri","Vena posterior atrii sinistri"]},
304:{en:["Anterior cardiac veins","Smallest cardiac veins"],la:["Venae cardiacae anteriores","Venae cordis minimae"]},
305:{en:["Fibrous pericardium (pericardial sac)","Serous pericardium"],la:["Pericardium fibrosum","Pericardium serosum"]},
306:{en:["Sternopericardial ligaments"],la:["Ligamenta sternopericardiaca"]},
307:{en:["Parietal layer","Visceral layer (epicardium)"],la:["Lamina parietalis","Lamina visceralis (epicardium)"]},
308:{en:["Anterior: manubrium of sternum","Posterior: first to fourth thoracic vertebrae","Superior: superior thoracic aperture","Inferior: superior border of heart"],la:["Anterior: manubrium sterni","Posterior: vertebrae thoracicae I–IV","Superior: apertura thoracis superior","Inferior: margo superior cordis"]},
309:{en:["Superior part of thymus, trachea, esophagus, aortic arch, superior vena cava, brachiocephalic veins, azygos vein","Thoracic duct, lymph nodes, phrenic nerves","Vagus nerves, sympathetic trunks"],la:["Pars superior thymi, trachea, oesophagus, arcus aortae, vena cava superior, venae brachiocephalicae, vena azygos","Ductus thoracicus, nodi lymphoidei, nervi phrenici","Nervi vagi, trunci sympathici"]},
310:{en:["Anterior: body of sternum","Posterior: anterior surface of pericardium"],la:["Anterior: corpus sterni","Posterior: facies anterior pericardii"]},
311:{en:["Inferior part of thymus, lymph nodes"],la:["Pars inferior thymi, nodi lymphoidei"]},
312:{en:["Anterior: anterior surface of pericardium","Posterior: posterior surface of pericardium"],la:["Anterior: facies anterior pericardii","Posterior: facies posterior pericardii"]},
313:{en:["Heart, ascending aorta, pulmonary arteries, pulmonary veins, superior vena cava, phrenic nerves"],la:["Cor, aorta ascendens, arteriae pulmonales, venae pulmonales, vena cava superior, nervi phrenici"]},
314:{en:["Anterior: posterior surface of pericardium","Posterior: fifth to twelfth thoracic vertebrae"],la:["Anterior: facies posterior pericardii","Posterior: vertebrae thoracicae V–XII"]},
315:{en:["Bronchi, esophagus, thoracic aorta","Azygos vein, hemiazygos vein, thoracic duct","Lymph nodes, vagus nerves, sympathetic trunks"],la:["Bronchi, oesophagus, aorta thoracica","Vena azygos, vena hemiazygos, ductus thoracicus","Nodi lymphoidei, nervi vagi, trunci sympathici"]},
316:{en:["Brachiocephalic trunk","Left common carotid artery","Left subclavian artery"],la:["Truncus brachiocephalicus","Arteria carotis communis sinistra","Arteria subclavia sinistra"]},
317:{en:["Bronchial arteries","Esophageal arteries"],la:["Arteriae bronchiales","Arteriae oesophageales"]},
318:{en:["Posterior intercostal arteries","Superior phrenic arteries"],la:["Arteriae intercostales posteriores","Arteriae phrenicae superiores"]},
319:{en:["Azygos vein","Hemiazygos vein","Accessory hemiazygos vein"],la:["Vena azygos","Vena hemiazygos","Vena hemiazygos accessoria"]},
320:{en:["Intercostal veins","Esophageal veins","Bronchial veins","Pericardial veins","Mediastinal veins","Superior phrenic veins"],la:["Venae intercostales","Venae oesophageales","Venae bronchiales","Venae pericardiacae","Venae mediastinales","Venae phrenicae superiores"]},
321:{en:["Cisterna chyli","Intestinal lymphatic trunks and lumbar lymphatic trunks"],la:["Cisterna chyli","Trunci intestinales et trunci lumbales"]},
322:{en:["Left subclavian lymphatic trunk","Left jugular lymphatic trunk","Left bronchomediastinal lymphatic trunk"],la:["Truncus subclavius sinister","Truncus jugularis sinister","Truncus bronchomediastinalis sinister"]},
323:{en:["Pulmonary lymph nodes","Bronchopulmonary lymph nodes","Tracheobronchial lymph nodes","Paratracheal lymph nodes"],la:["Nodi lymphoidei pulmonales","Nodi lymphoidei bronchopulmonales","Nodi lymphoidei tracheobronchiales","Nodi lymphoidei paratracheales"]},
324:{en:["Greater splanchnic nerve","Lesser splanchnic nerve","Thoracic cardiac nerves","Pulmonary branches","Aortic branches"],la:["Nervus splanchnicus major","Nervus splanchnicus minor","Nervi cardiaci thoracici","Rami pulmonales","Rami aortici"]}
});
