window.ANATOMY_TRANSLATIONS=Object.assign(window.ANATOMY_TRANSLATIONS||{}, {
325:{en:["Camper fascia (fatty layer of superficial fascia)","Scarpa fascia (membranous layer of superficial fascia)"],la:["Stratum adiposum telae subcutaneae abdominis","Stratum membranosum telae subcutaneae abdominis"]},
326:{en:["External oblique muscle of abdomen","Internal oblique muscle of abdomen","Transversus abdominis muscle","Rectus abdominis muscle","Pyramidalis muscle"],la:["Musculus obliquus externus abdominis","Musculus obliquus internus abdominis","Musculus transversus abdominis","Musculus rectus abdominis","Musculus pyramidalis"]},
327:{en:["Inguinal ligament"],la:["Ligamentum inguinale"]},
328:{en:["Lacunar ligament"],la:["Ligamentum lacunare"]},
329:{en:["Reflected ligament"],la:["Ligamentum reflexum"]},
330:{en:["Subcostal nerve"],la:["Nervus subcostalis"]},
331:{en:["External oblique muscle of abdomen"],la:["Musculus obliquus externus abdominis"]},
332:{en:["Transversalis fascia"],la:["Fascia transversalis"]},
333:{en:["Internal oblique muscle of abdomen","Transversus abdominis muscle"],la:["Musculus obliquus internus abdominis","Musculus transversus abdominis"]},
334:{en:["Inguinal ligament"],la:["Ligamentum inguinale"]},
335:{en:["Spermatic cord (round ligament of uterus in the female)","Ilioinguinal nerve"],la:["Funiculus spermaticus (ligamentum teres uteri in femina)","Nervus ilioinguinalis"]},
336:{en:["Iliacus muscle","Psoas major muscle","Quadratus lumborum muscle"],la:["Musculus iliacus","Musculus psoas major","Musculus quadratus lumborum"]},
337:{en:["Superior, inferior, and superficial epigastric arteries","Superficial and deep circumflex iliac arteries","Tenth and eleventh posterior intercostal arteries","Subcostal and lumbar arteries"],la:["Arteriae epigastricae superior, inferior et superficialis","Arteriae circumflexae ilium superficialis et profunda","Arteriae intercostales posteriores X et XI","Arteria subcostalis et arteriae lumbales"]},
338:{en:["Pubic branch","Cremasteric artery"],la:["Ramus pubicus","Arteria cremasterica"]},
339:{en:["Above the umbilicus: axillary lymph nodes","Below the umbilicus: superficial inguinal lymph nodes"],la:["Supra umbilicum: nodi lymphoidei axillares","Infra umbilicum: nodi lymphoidei inguinales superficiales"]},
340:{en:["Parasternal lymph nodes","External iliac lymph nodes","Lumbar lymph nodes"],la:["Nodi lymphoidei parasternales","Nodi lymphoidei iliaci externi","Nodi lymphoidei lumbales"]},
341:{en:["Intercostal nerves","Subcostal nerve","Iliohypogastric nerve","Ilioinguinal nerve"],la:["Nervi intercostales","Nervus subcostalis","Nervus iliohypogastricus","Nervus ilioinguinalis"]},
342:{en:["Lesser curvature: lesser omentum","Greater curvature: greater omentum"],la:["Curvatura minor: omentum minus","Curvatura major: omentum majus"]},
343:{en:["Upper right: liver","Upper left: left costal arch","Inferior: transverse colon"],la:["Superius dextrum: hepar","Superius sinistrum: arcus costalis sinister","Inferius: colon transversum"]},
344:{en:["Spleen","Left kidney","Left suprarenal gland","Pancreas"],la:["Splen","Ren sinister","Glandula suprarenalis sinistra","Pancreas"]},
345:{en:["Left gastric artery","Right gastric artery","Short gastric arteries","Left gastroomental artery","Right gastroomental artery"],la:["Arteria gastrica sinistra","Arteria gastrica dextra","Arteriae gastricae breves","Arteria gastroomentalis sinistra","Arteria gastroomentalis dextra"]},
346:{en:["Left gastric lymph nodes","Right gastric lymph nodes","Left gastroomental lymph nodes","Right gastroomental lymph nodes","Pyloric lymph nodes"],la:["Nodi lymphoidei gastrici sinistri","Nodi lymphoidei gastrici dextri","Nodi lymphoidei gastroomentales sinistri","Nodi lymphoidei gastroomentales dextri","Nodi lymphoidei pylorici"]},
347:{en:["Superior pancreaticoduodenal arteries","Inferior pancreaticoduodenal arteries"],la:["Arteriae pancreaticoduodenales superiores","Arteriae pancreaticoduodenales inferiores"]},
348:{en:["Superior mesenteric artery","Jejunal arteries","Ileal arteries"],la:["Arteria mesenterica superior","Arteriae jejunales","Arteriae ileales"]},
349:{en:["Colic branch","Anterior cecal artery","Posterior cecal artery","Appendicular artery"],la:["Ramus colicus","Arteria caecalis anterior","Arteria caecalis posterior","Arteria appendicularis"]},
350:{en:["Taeniae coli","Haustra of colon","Omental appendices"],la:["Taeniae coli","Haustra coli","Appendices omentales"]},
351:{en:["Ileocolic artery","Right colic artery","Middle colic artery","Left colic artery","Sigmoid arteries","Superior rectal artery"],la:["Arteria ileocolica","Arteria colica dextra","Arteria colica media","Arteria colica sinistra","Arteriae sigmoideae","Arteria rectalis superior"]},
352:{en:["Epicolic lymph nodes","Paracolic lymph nodes","Intermediate mesenteric lymph nodes","Superior mesenteric lymph nodes","Inferior mesenteric lymph nodes"],la:["Nodi lymphoidei epicolici","Nodi lymphoidei paracolici","Nodi lymphoidei mesenterici intermedii","Nodi lymphoidei mesenterici superiores","Nodi lymphoidei mesenterici inferiores"]},
353:{en:["Gastric impression","Esophageal impression"],la:["Impressio gastrica","Impressio oesophagea"]},
354:{en:["Duodenal impression","Colic impression","Renal impression","Suprarenal impression"],la:["Impressio duodenalis","Impressio colica","Impressio renalis","Impressio suprarenalis"]},
355:{en:["Anterior part: fissure for round ligament — round ligament of liver","Posterior part: fissure for ligamentum venosum — ligamentum venosum"],la:["Pars anterior: fissura ligamenti teretis — ligamentum teres hepatis","Pars posterior: fissura ligamenti venosi — ligamentum venosum"]},
356:{en:["Anterior part: fossa for gallbladder — gallbladder","Posterior part: groove for vena cava — inferior vena cava"],la:["Pars anterior: fossa vesicae biliaris — vesica biliaris","Pars posterior: sulcus venae cavae — vena cava inferior"]},
357:{en:["Falciform ligament of liver","Triangular ligaments","Coronary ligament of liver","Lesser omentum"],la:["Ligamentum falciforme hepatis","Ligamenta triangularia","Ligamentum coronarium hepatis","Omentum minus"]},
358:{en:["Subphrenic recess","Subhepatic recess"],la:["Recessus subphrenicus","Recessus subhepaticus"]},
359:{en:["Proper hepatic artery","Hepatic portal vein"],la:["Arteria hepatica propria","Vena portae hepatis"]},
360:{en:["Hepatic veins"],la:["Venae hepaticae"]},
361:{en:["Portal vein — azygos vein — superior vena cava","Portal vein — rectal veins — inferior vena cava","Portal vein — paraumbilical veins — superficial veins of anterior abdominal wall — vena cava","Portal vein — retroperitoneal veins — inferior vena cava"],la:["Vena portae hepatis — vena azygos — vena cava superior","Vena portae hepatis — venae rectales — vena cava inferior","Vena portae hepatis — venae paraumbilicales — venae superficiales parietis abdominalis anterioris — vena cava","Vena portae hepatis — venae retroperitoneales — vena cava inferior"]},
362:{en:["Splenomegaly","Esophageal varices","Caput medusae","Hemorrhoids"],la:["Splenomegalia","Varices oesophageae","Caput Medusae","Haemorrhoides"]},
363:{en:["Superior pancreaticoduodenal arteries","Inferior pancreaticoduodenal arteries","Splenic artery"],la:["Arteriae pancreaticoduodenales superiores","Arteriae pancreaticoduodenales inferiores","Arteria splenica"]},
364:{en:["Gastrosplenic ligament","Phrenicosplenic ligament"],la:["Ligamentum gastrosplenicum","Ligamentum phrenicosplenicum"]},
365:{en:["Hepatogastric ligament","Hepatoduodenal ligament"],la:["Ligamentum hepatogastricum","Ligamentum hepatoduodenale"]},
366:{en:["Median umbilical fold — median umbilical ligament","Medial umbilical fold — obliterated umbilical artery (medial umbilical ligament)","Lateral umbilical fold — inferior epigastric vessels"],la:["Plica umbilicalis mediana — ligamentum umbilicale medianum","Plica umbilicalis medialis — arteria umbilicalis obliterata (ligamentum umbilicale mediale)","Plica umbilicalis lateralis — vasa epigastrica inferiora"]},
367:{en:["Supravesical fossa","Medial inguinal fossa","Lateral inguinal fossa"],la:["Fossa supravesicalis","Fossa inguinalis medialis","Fossa inguinalis lateralis"]},
368:{en:["Superior suprarenal arteries ← inferior phrenic artery","Middle suprarenal artery ← abdominal aorta or superior mesenteric artery","Inferior suprarenal artery ← renal artery"],la:["Arteriae suprarenales superiores ← arteria phrenica inferior","Arteria suprarenalis media ← aorta abdominalis vel arteria mesenterica superior","Arteria suprarenalis inferior ← arteria renalis"]},
369:{en:["Left suprarenal vein → left renal vein","Right suprarenal vein → inferior vena cava"],la:["Vena suprarenalis sinistra → vena renalis sinistra","Vena suprarenalis dextra → vena cava inferior"]},
370:{en:["Celiac trunk","Superior mesenteric artery","Inferior mesenteric artery"],la:["Truncus coeliacus","Arteria mesenterica superior","Arteria mesenterica inferior"]},
371:{en:["Middle suprarenal artery","Renal artery","Testicular or ovarian artery"],la:["Arteria suprarenalis media","Arteria renalis","Arteria testicularis vel arteria ovarica"]},
372:{en:["Inferior phrenic arteries","Lumbar arteries"],la:["Arteriae phrenicae inferiores","Arteriae lumbales"]},
373:{en:["Left gastric artery","Splenic artery","Common hepatic artery"],la:["Arteria gastrica sinistra","Arteria splenica","Arteria hepatica communis"]},
374:{en:["Left gastroomental artery","Short gastric arteries","Pancreatic branches","Splenic branches"],la:["Arteria gastroomentalis sinistra","Arteriae gastricae breves","Rami pancreatici","Rami splenici"]},
375:{en:["Proper hepatic artery","Right gastric artery","Gastroduodenal artery"],la:["Arteria hepatica propria","Arteria gastrica dextra","Arteria gastroduodenalis"]},
376:{en:["Cystic artery"],la:["Arteria cystica"]},
377:{en:["Right gastroomental artery","Superior pancreaticoduodenal arteries"],la:["Arteria gastroomentalis dextra","Arteriae pancreaticoduodenales superiores"]},
378:{en:["Inferior pancreaticoduodenal arteries","Jejunal arteries","Ileal arteries","Ileocolic artery","Right colic artery","Middle colic artery"],la:["Arteriae pancreaticoduodenales inferiores","Arteriae jejunales","Arteriae ileales","Arteria ileocolica","Arteria colica dextra","Arteria colica media"]},
379:{en:["Left colic artery","Sigmoid arteries","Superior rectal artery"],la:["Arteria colica sinistra","Arteriae sigmoideae","Arteria rectalis superior"]},
380:{en:["Deep circumflex iliac artery","Inferior epigastric artery"],la:["Arteria circumflexa ilium profunda","Arteria epigastrica inferior"]},
381:{en:["Lumbar veins","Testicular or ovarian veins","Renal veins","Hepatic veins","Inferior phrenic veins"],la:["Venae lumbales","Venae testiculares vel venae ovaricae","Venae renales","Venae hepaticae","Venae phrenicae inferiores"]},
382:{en:["Iliohypogastric nerve","Ilioinguinal nerve","Lateral cutaneous nerve of thigh","Femoral nerve"],la:["Nervus iliohypogastricus","Nervus ilioinguinalis","Nervus cutaneus femoris lateralis","Nervus femoralis"]},
383:{en:["Obturator nerve"],la:["Nervus obturatorius"]},
384:{en:["Genitofemoral nerve"],la:["Nervus genitofemoralis"]}
});
