window.ANATOMY_TRANSLATIONS=Object.assign(window.ANATOMY_TRANSLATIONS||{}, {
1:{en:["Sternoclavicular joint","Acromioclavicular joint"],la:["Articulatio sternoclavicularis","Articulatio acromioclavicularis"]},
2:{en:["Sternoclavicular ligament","Costoclavicular ligament","Interclavicular ligament"],la:["Ligamentum sternoclaviculare","Ligamentum costoclaviculare","Ligamentum interclaviculare"]},
3:{en:["Acromioclavicular ligament","Coracoclavicular ligament"],la:["Ligamentum acromioclaviculare","Ligamentum coracoclaviculare"]},
4:{en:["Trapezoid ligament","Conoid ligament"],la:["Ligamentum trapezoideum","Ligamentum conoideum"]},
5:{en:["Coracoacromial ligament","Coracohumeral ligament"],la:["Ligamentum coracoacromiale","Ligamentum coracohumerale"]},
6:{en:["Subscapularis muscle","Supraspinatus muscle","Infraspinatus muscle","Teres minor muscle"],la:["Musculus subscapularis","Musculus supraspinatus","Musculus infraspinatus","Musculus teres minor"]},
7:{en:["Humeroulnar joint","Humeroradial joint","Proximal radioulnar joint"],la:["Articulatio humeroulnaris","Articulatio humeroradialis","Articulatio radioulnaris proximalis"]},
8:{en:["Proximal radioulnar joint","Distal radioulnar joint","Interosseous membrane of forearm"],la:["Articulatio radioulnaris proximalis","Articulatio radioulnaris distalis","Membrana interossea antebrachii"]},
9:{en:["Radiocarpal joint","Midcarpal joint","Intercarpal joints"],la:["Articulatio radiocarpalis","Articulatio mediocarpalis","Articulationes intercarpales"]},
10:{en:["Trapezius muscle","Levator scapulae muscle","Rhomboid muscles","Serratus anterior muscle"],la:["Musculus trapezius","Musculus levator scapulae","Musculi rhomboidei","Musculus serratus anterior"]},
11:{en:["Long thoracic nerve"],la:["Nervus thoracicus longus"]},
12:{en:["Pectoralis minor muscle","Subclavius muscle"],la:["Musculus pectoralis minor","Musculus subclavius"]},
13:{en:["Medial pectoral nerve"],la:["Nervus pectoralis medialis"]},
14:{en:["Nerve to subclavius"],la:["Nervus subclavius"]},
15:{en:["Dorsal: latissimus dorsi muscle","Ventral: pectoralis major muscle"],la:["Dorsaliter: musculus latissimus dorsi","Ventraliter: musculus pectoralis major"]},
16:{en:["Thoracodorsal nerve"],la:["Nervus thoracodorsalis"]},
17:{en:["Lateral pectoral nerve","Part of the medial pectoral nerve"],la:["Nervus pectoralis lateralis","Pars nervi pectoralis medialis"]},
18:{en:["Deltoid muscle","Coracobrachialis muscle","Teres major muscle","Subscapularis muscle","Supraspinatus muscle","Infraspinatus muscle","Teres minor muscle"],la:["Musculus deltoideus","Musculus coracobrachialis","Musculus teres major","Musculus subscapularis","Musculus supraspinatus","Musculus infraspinatus","Musculus teres minor"]},
19:{en:["Axillary nerve"],la:["Nervus axillaris"]},
20:{en:["Musculocutaneous nerve"],la:["Nervus musculocutaneus"]},
21:{en:["Subscapular nerve"],la:["Nervus subscapularis"]},
22:{en:["Subscapular nerve"],la:["Nervus subscapularis"]},
23:{en:["Suprascapular nerve"],la:["Nervus suprascapularis"]},
24:{en:["Suprascapular nerve"],la:["Nervus suprascapularis"]},
25:{en:["Axillary nerve"],la:["Nervus axillaris"]},
26:{en:["Pectoralis major muscle","Pectoralis minor muscle"],la:["Musculus pectoralis major","Musculus pectoralis minor"]},
27:{en:["Latissimus dorsi muscle","Subscapularis muscle","Teres major muscle"],la:["Musculus latissimus dorsi","Musculus subscapularis","Musculus teres major"]},
28:{en:["Serratus anterior muscle"],la:["Musculus serratus anterior"]},
29:{en:["Humerus"],la:["Humerus"]},
30:{en:["Teres major muscle","Teres minor muscle","Long head of triceps brachii muscle"],la:["Musculus teres major","Musculus teres minor","Caput longum musculi tricipitis brachii"]},
31:{en:["Circumflex scapular artery and vein"],la:["Arteria et vena circumflexae scapulae"]},
32:{en:["Teres major muscle","Teres minor muscle","Long head of triceps brachii muscle","Humerus"],la:["Musculus teres major","Musculus teres minor","Caput longum musculi tricipitis brachii","Humerus"]},
33:{en:["Posterior circumflex humeral artery","Axillary nerve"],la:["Arteria circumflexa humeri posterior","Nervus axillaris"]},
34:{en:["Biceps brachii muscle","Brachialis muscle"],la:["Musculus biceps brachii","Musculus brachialis"]},
35:{en:["Musculocutaneous nerve"],la:["Nervus musculocutaneus"]},
36:{en:["Musculocutaneous nerve","Radial nerve"],la:["Nervus musculocutaneus","Nervus radialis"]},
37:{en:["Triceps brachii muscle","Anconeus muscle"],la:["Musculus triceps brachii","Musculus anconeus"]},
38:{en:["Radial nerve"],la:["Nervus radialis"]},
39:{en:["Radial nerve"],la:["Nervus radialis"]},
40:{en:["Medial intermuscular septum of arm","Lateral intermuscular septum of arm"],la:["Septum intermusculare brachii mediale","Septum intermusculare brachii laterale"]},
41:{en:["Pronator teres muscle","Flexor carpi radialis muscle","Palmaris longus muscle","Flexor carpi ulnaris muscle"],la:["Musculus pronator teres","Musculus flexor carpi radialis","Musculus palmaris longus","Musculus flexor carpi ulnaris"]},
42:{en:["Flexor carpi radialis muscle","Palmaris longus muscle","Flexor carpi ulnaris muscle"],la:["Musculus flexor carpi radialis","Musculus palmaris longus","Musculus flexor carpi ulnaris"]},
43:{en:["Median nerve"],la:["Nervus medianus"]},
44:{en:["Median nerve"],la:["Nervus medianus"]},
45:{en:["Median nerve"],la:["Nervus medianus"]},
46:{en:["Ulnar nerve"],la:["Nervus ulnaris"]},
47:{en:["Flexor digitorum superficialis muscle"],la:["Musculus flexor digitorum superficialis"]},
48:{en:["Median nerve"],la:["Nervus medianus"]},
49:{en:["Flexor digitorum profundus muscle","Flexor pollicis longus muscle","Pronator quadratus muscle"],la:["Musculus flexor digitorum profundus","Musculus flexor pollicis longus","Musculus pronator quadratus"]},
50:{en:["Flexor digitorum profundus muscle","Flexor pollicis longus muscle"],la:["Musculus flexor digitorum profundus","Musculus flexor pollicis longus"]},
51:{en:["Median nerve","Ulnar half: ulnar nerve"],la:["Nervus medianus","Dimidium ulnare: nervus ulnaris"]},
52:{en:["Median nerve"],la:["Nervus medianus"]},
53:{en:["Median nerve"],la:["Nervus medianus"]},
54:{en:["Brachioradialis muscle","Extensor carpi radialis longus muscle","Extensor carpi radialis brevis muscle","Extensor digitorum muscle","Extensor digiti minimi muscle","Extensor carpi ulnaris muscle"],la:["Musculus brachioradialis","Musculus extensor carpi radialis longus","Musculus extensor carpi radialis brevis","Musculus extensor digitorum","Musculus extensor digiti minimi","Musculus extensor carpi ulnaris"]},
55:{en:["Radial nerve"],la:["Nervus radialis"]},
56:{en:["Lateral: brachioradialis muscle","Medial: pronator teres muscle"],la:["Lateraliter: musculus brachioradialis","Medialiter: musculus pronator teres"]},
57:{en:["Tendon of biceps brachii muscle"],la:["Tendo musculi bicipitis brachii"]},
58:{en:["Brachial artery","Median nerve"],la:["Arteria brachialis","Nervus medianus"]},
59:{en:["Radial nerve"],la:["Nervus radialis"]},
60:{en:["Radial nerve"],la:["Nervus radialis"]},
61:{en:["Radial nerve"],la:["Nervus radialis"]},
62:{en:["Radial nerve"],la:["Nervus radialis"]},
63:{en:["Radial nerve"],la:["Nervus radialis"]},
64:{en:["Supinator muscle","Abductor pollicis longus muscle","Extensor pollicis brevis muscle","Extensor pollicis longus muscle","Extensor indicis muscle"],la:["Musculus supinator","Musculus abductor pollicis longus","Musculus extensor pollicis brevis","Musculus extensor pollicis longus","Musculus extensor indicis"]},
65:{en:["Radial nerve"],la:["Nervus radialis"]},
66:{en:["Radial nerve"],la:["Nervus radialis"]},
67:{en:["Radial nerve"],la:["Nervus radialis"]},
68:{en:["Radial nerve"],la:["Nervus radialis"]},
69:{en:["Radial fossa","Anatomical snuffbox"],la:["Fossa radialis","Foveola radialis"]},
70:{en:["Radial nerve"],la:["Nervus radialis"]},
71:{en:["Palmar: flexor retinaculum","Dorsal: extensor retinaculum"],la:["Palmariter: retinaculum flexorum","Dorsaliter: retinaculum extensorum"]},
72:{en:["Scaphoid bone","Trapezium","Pisiform bone","Hamate bone"],la:["Os scaphoideum","Os trapezium","Os pisiforme","Os hamatum"]},
73:{en:["Tendon of abductor pollicis longus muscle","Tendon of extensor pollicis brevis muscle"],la:["Tendo musculi abductoris pollicis longi","Tendo musculi extensoris pollicis brevis"]},
74:{en:["Tendon of extensor carpi radialis longus muscle","Tendon of extensor carpi radialis brevis muscle"],la:["Tendo musculi extensoris carpi radialis longi","Tendo musculi extensoris carpi radialis brevis"]},
75:{en:["Tendon of extensor pollicis longus muscle"],la:["Tendo musculi extensoris pollicis longi"]},
76:{en:["Tendon of extensor indicis muscle","Tendon of extensor digitorum muscle"],la:["Tendo musculi extensoris indicis","Tendo musculi extensoris digitorum"]},
77:{en:["Tendon of extensor digiti minimi muscle"],la:["Tendo musculi extensoris digiti minimi"]},
78:{en:["Tendon of extensor carpi ulnaris muscle"],la:["Tendo musculi extensoris carpi ulnaris"]},
79:{en:["Abductor pollicis brevis muscle","Opponens pollicis muscle","Flexor pollicis brevis muscle","Adductor pollicis muscle"],la:["Musculus abductor pollicis brevis","Musculus opponens pollicis","Musculus flexor pollicis brevis","Musculus adductor pollicis"]},
80:{en:["Median nerve"],la:["Nervus medianus"]},
81:{en:["Median nerve"],la:["Nervus medianus"]},
82:{en:["Median nerve"],la:["Nervus medianus"]},
83:{en:["Abductor digiti minimi muscle","Opponens digiti minimi muscle","Flexor digiti minimi brevis muscle"],la:["Musculus abductor digiti minimi","Musculus opponens digiti minimi","Musculus flexor digiti minimi brevis"]},
84:{en:["Ulnar nerve"],la:["Nervus ulnaris"]},
85:{en:["Ulnar nerve"],la:["Nervus ulnaris"]},
86:{en:["Ulnar nerve"],la:["Nervus ulnaris"]},
87:{en:["Adductor pollicis muscle","Lumbrical muscles","Interosseous muscles"],la:["Musculus adductor pollicis","Musculi lumbricales","Musculi interossei"]},
88:{en:["Ulnar nerve"],la:["Nervus ulnaris"]},
89:{en:["Ulnar nerve"],la:["Nervus ulnaris"]},
90:{en:["Trapezius muscle","Levator scapulae muscle","Rhomboid muscles"],la:["Musculus trapezius","Musculus levator scapulae","Musculi rhomboidei"]},
91:{en:["Trapezius muscle","Latissimus dorsi muscle","Pectoralis minor muscle"],la:["Musculus trapezius","Musculus latissimus dorsi","Musculus pectoralis minor"]},
92:{en:["Serratus anterior muscle","Pectoralis minor muscle","Pectoralis major muscle"],la:["Musculus serratus anterior","Musculus pectoralis minor","Musculus pectoralis major"]},
93:{en:["Trapezius muscle","Rhomboid muscles","Latissimus dorsi muscle"],la:["Musculus trapezius","Musculi rhomboidei","Musculus latissimus dorsi"]},
94:{en:["Trapezius muscle","Serratus anterior muscle"],la:["Musculus trapezius","Musculus serratus anterior"]},
95:{en:["Rhomboid muscles","Levator scapulae muscle","Pectoralis major muscle","Pectoralis minor muscle","Latissimus dorsi muscle"],la:["Musculi rhomboidei","Musculus levator scapulae","Musculus pectoralis major","Musculus pectoralis minor","Musculus latissimus dorsi"]},
96:{en:["Pectoralis major muscle","Deltoid muscle","Coracobrachialis muscle","Biceps brachii muscle"],la:["Musculus pectoralis major","Musculus deltoideus","Musculus coracobrachialis","Musculus biceps brachii"]},
97:{en:["Latissimus dorsi muscle","Deltoid muscle","Teres major muscle","Triceps brachii muscle"],la:["Musculus latissimus dorsi","Musculus deltoideus","Musculus teres major","Musculus triceps brachii"]},
98:{en:["Supraspinatus muscle","Deltoid muscle","Triceps brachii muscle"],la:["Musculus supraspinatus","Musculus deltoideus","Musculus triceps brachii"]},
99:{en:["Pectoralis major muscle","Latissimus dorsi muscle","Subscapularis muscle","Teres major muscle","Coracobrachialis muscle","Teres minor muscle"],la:["Musculus pectoralis major","Musculus latissimus dorsi","Musculus subscapularis","Musculus teres major","Musculus coracobrachialis","Musculus teres minor"]},
100:{en:["Subscapularis muscle","Teres major muscle","Pectoralis major muscle","Deltoid muscle","Latissimus dorsi muscle"],la:["Musculus subscapularis","Musculus teres major","Musculus pectoralis major","Musculus deltoideus","Musculus latissimus dorsi"]},
101:{en:["Infraspinatus muscle","Teres minor muscle","Deltoid muscle"],la:["Musculus infraspinatus","Musculus teres minor","Musculus deltoideus"]},
102:{en:["Brachialis muscle","Biceps brachii muscle","Brachioradialis muscle"],la:["Musculus brachialis","Musculus biceps brachii","Musculus brachioradialis"]},
103:{en:["Triceps brachii muscle","Anconeus muscle"],la:["Musculus triceps brachii","Musculus anconeus"]},
104:{en:["Pronator quadratus muscle","Pronator teres muscle"],la:["Musculus pronator quadratus","Musculus pronator teres"]},
105:{en:["Supinator muscle","Biceps brachii muscle"],la:["Musculus supinator","Musculus biceps brachii"]},
106:{en:["Superior thoracic artery"],la:["Arteria thoracica superior"]},
107:{en:["Thoracoacromial artery","Lateral thoracic artery"],la:["Arteria thoracoacromialis","Arteria thoracica lateralis"]},
108:{en:["Subscapular artery","Anterior circumflex humeral artery","Posterior circumflex humeral artery"],la:["Arteria subscapularis","Arteria circumflexa humeri anterior","Arteria circumflexa humeri posterior"]},
109:{en:["Thoracodorsal artery","Circumflex scapular artery"],la:["Arteria thoracodorsalis","Arteria circumflexa scapulae"]},
110:{en:["Anterior circumflex humeral artery","Suprascapular artery","Thoracoacromial artery","Deep artery of arm"],la:["Arteria circumflexa humeri anterior","Arteria suprascapularis","Arteria thoracoacromialis","Arteria profunda brachii"]},
111:{en:["Deep artery of arm","Superior ulnar collateral artery","Inferior ulnar collateral artery"],la:["Arteria profunda brachii","Arteria collateralis ulnaris superior","Arteria collateralis ulnaris inferior"]},
112:{en:["Middle collateral artery","Radial collateral artery"],la:["Arteria collateralis media","Arteria collateralis radialis"]},
113:{en:["Radial recurrent artery","Palmar carpal branch","Dorsal carpal branch","Superficial palmar branch","Princeps pollicis artery","Deep palmar arch"],la:["Arteria recurrens radialis","Ramus carpalis palmaris","Ramus carpalis dorsalis","Ramus palmaris superficialis","Arteria princeps pollicis","Arcus palmaris profundus"]},
114:{en:["Ulnar recurrent artery","Common interosseous artery","Dorsal carpal branch","Palmar carpal branch","Deep palmar branch","Superficial palmar arch"],la:["Arteria recurrens ulnaris","Arteria interossea communis","Ramus carpalis dorsalis","Ramus carpalis palmaris","Ramus palmaris profundus","Arcus palmaris superficialis"]},
115:{en:["Bicipital aponeurosis"],la:["Aponeurosis musculi bicipitis brachii"]},
116:{en:["Deep lymph nodes","Cubital lymph nodes","Axillary lymph nodes"],la:["Nodi lymphoidei profundi","Nodi lymphoidei cubitales","Nodi lymphoidei axillares"]},
117:{en:["Pectoral axillary lymph nodes","Lateral axillary lymph nodes","Subscapular axillary lymph nodes","Central axillary lymph nodes","Apical axillary lymph nodes"],la:["Nodi lymphoidei axillares pectorales","Nodi lymphoidei axillares laterales","Nodi lymphoidei axillares subscapulares","Nodi lymphoidei axillares centrales","Nodi lymphoidei axillares apicales"]},
118:{en:["Dorsal scapular nerve","Long thoracic nerve","Suprascapular nerve"],la:["Nervus dorsalis scapulae","Nervus thoracicus longus","Nervus suprascapularis"]},
119:{en:["Lateral pectoral nerve"],la:["Nervus pectoralis lateralis"]},
120:{en:["Medial pectoral nerve","Medial cutaneous nerve of arm","Medial cutaneous nerve of forearm"],la:["Nervus pectoralis medialis","Nervus cutaneus brachii medialis","Nervus cutaneus antebrachii medialis"]},
121:{en:["Subscapular nerves","Thoracodorsal nerve"],la:["Nervi subscapulares","Nervus thoracodorsalis"]}
});
